### ISSUE TITLE
Support evaluate on hover

### ISSUE THREAD

**Issue by csholmq** [WebFreak001/code-debug#10]
In order for this to work, it appears that the  extension needs to support 
```
/** The debug adapter supports a (side effect free) evaluate request for data hovers. */
supportsEvaluateForHovers?: boolean;
```

https://github.com/Microsoft/vscode/issues/2745#issuecomment-181765580
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L489

**Comment by WebFreak001** [comment]
:+1: gonna implement

**Comment by WebFreak001** [comment]
Actually Im not quite sure if this would make sense, as it would only support global variables because variables in functions keep changing, for example children of a class. Im gonna try and do my best

**Comment by csholmq** [comment]
But it makes total sense for global variables! :) Especially for structural languages such as C.

Here's how I use your plugin with my remote target (GDB) and polling variables using Watch:

![gdb_remote_debug](https://cloud.githubusercontent.com/assets/1297882/12914401/716b6e7a-cf24-11e5-950c-64c16397836c.gif)

https://github.com/Microsoft/vscode/issues/2833

**Comment by WebFreak001** [comment]
I dont think this will actually work for running symbols if not using gdbserver or something else.

For me it gives an error when trying to access a global variable while the program is running: `Cannot access memory at address 0x6008f4`

**Comment by csholmq** [comment]
@WebFreak001 I get that when I use the wrong offset. Does it work for you using a Watch?

**Comment by WebFreak001** [comment]
I am currently testing it in the watch. It only works when the program is paused, otherwise it tells me "cannot access memory". Here is my used code:

```c
#include <stdio.h>

int GlobalVariable = 0;

int main() {
	printf("Hello World\n");
	while(1) {
		GlobalVariable++;
	}
	return 0;
}
```

**Comment by csholmq** [comment]
Well I'm in a remote target debug; don't know if that makes a different. I just press Start once and then a `add-symbol-file My_Elf_File.elf 0x8020000` in the console.

If I press Continue or Step, everything stops working.

```
"name": "Debug GDB",
"type": "gdb",
"request": "attach",
"target": ":4444",
"remote": true,
```

**Comment by WebFreak001** [comment]
In theory its implemented now. However vscode does not seem to call evaluate for me. Maybe its implemented in the feburary release?

**Comment by csholmq** [comment]
Great. According to https://github.com/Microsoft/vscode/issues/2745#issuecomment-181765580 they need to add support in VSCode to evaluate whilst not paused.

**Comment by WebFreak001** [comment]
I mean it also doesn't get called when its paused (on a breakpoint)

**Comment by csholmq** [comment]
Hmm. Then I don't really know what's going on.

Is there a difference to "Paused" and "Stopped"?

**Comment by WebFreak001** [comment]
There is only a StopEvent that I need to send when the program pauses. If it completely quits I need to send a TerminatedEvent. I think this is a vscode bug or they only have it in the current development version. I only have the January release

**Comment by csholmq** [comment]
Not really sure of the current status atm. But now when I start my remote debug it seems to stop at inside an arbitrary function (same every time, with no breakpoint set) and spoofs a call stack.

I can also hover variables so that part seems to work (as long as it thinks it's paused).

![image](https://cloud.githubusercontent.com/assets/1297882/12952080/8c4be07a-d015-11e5-9b66-1f1f3e74d5a8.png)

**Comment by WebFreak001** [comment]
now working in latest release!
