### ISSUE TITLE
cannot remotely debug arm linux

### ISSUE THREAD

**Issue by justin-romano** [WebFreak001/code-debug#100]
Seems like its using the local x86 gdb (host computer running windows) 
Does not seem to be a way to specifie using arm tool chain arm-none-eabi-gdb.exe

top error;
`Failed to attach: Remote 'g' packet reply is too long: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
`

console error:
```
warning: while parsing target description (at line 10): Target description specified unknown architecture "arm"
warning: Could not load XML target description; ignoring

```

**Comment by WebFreak001** [comment]
Try changing the `gdbpath` option in the debugger config to `arm-none-eabi-gdb.exe` then

**Comment by justin-romano** [comment]
Nice. undocumented feature. knew there to be one somewhere, 
How do i set gdb commands like sysroot?

**Comment by justin-romano** [comment]
Thats much better but not hitting breakpoints.
Getting bogus error msg from arm-none-eabi-gdb.exe path not found
Any ideas
**No source file named c:\src\orange\WiringOP-Zero\examples\hello.c.**
```
Reading /root/src/WiringOP-Zero/examples/hello from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
warning: A handler for the OS ABI "GNU/Linux" is not built into this configuration
of GDB.  Attempting to continue with the default arm settings.
Reading /root/src/WiringOP-Zero/examples/hello from remote target...
warning: A handler for the OS ABI "GNU/Linux" is not built into this configuration
of GDB.  Attempting to continue with the default arm settings.
Reading symbols from target:/root/src/WiringOP-Zero/examples/hello...
done.
0xb6fd7a40 in ?? ()
Not implemented stop reason (assuming exception): undefined
No source file named c:\src\orange\WiringOP-Zero\examples\hello.c.
[Inferior 1 (process 1928) exited normally]
```

**Comment by WebFreak001** [comment]
Need to add some way to rewrite paths there

**Comment by berdon** [comment]
This can be accomplished via the autorun configuration:

`"autorun": [
                "set substitute-path /root ."
            ]`

**Comment by dbgurevich2017** [comment]
I have the same problem trying to connect to gdbserver running on an ARM7 32bit CPU:

"failed to attach: remote 'g' packet reply is too long (expected 312 bytes, got 328 bytes) "

I am able to connect successfully on the command line with gdb-multiarch. My host environment is Ubuntu 20.04.

I edited the ~/.vscode/extensions/webfreak.debug-0.25.1/package.json and changed the gdbpath from "gdb" to "gdb-multiarch". 

Still getting the error popup.

What am I missing?

**Comment by GitMensch** [comment]
> I edited the ~/.vscode/extensions/webfreak.debug-0.25.1/package.json and changed the gdbpath from "gdb" to "gdb-multiarch".

You have to adjust the gdbpath in your launch configuration, not in the extension.

If you still have issues after doing so, please post your launch configuration and...

> I am able to connect successfully on the command line with gdb-multiarch. My host environment is Ubuntu 20.04.

... what you do exactly to connect on the command line. This should be enough data to analyze more.

**Comment by GitMensch** [comment]
Rewriting the remote paths work now fine using the `sourceFileMap` setting. Please recheck with current release for possible open points.

Side note: instead of using a target specific gdb like `arm-none-eabi-gdb.exe` you may want to check using `gdb-multiarch.exe` from MSYS2 project -> one to rule them all, with full python support.
