### ISSUE TITLE
Missing GDB in Path results in unhelpful error

### ISSUE THREAD

**Issue by KytoDragon** [WebFreak001/code-debug#102]
I created a launch.json file for debugging with gdb but forgot to put gdb.exe on the path and got the following error message:

`Debug adapter process has terminated unexpectedly: Cannot read property 'toLowerCase' of undefined`

Please provide a more helpful error message to make it easier to catch problems like that.

**Comment by WebFreak001** [comment]
Uh that's an error in the extension, are you sure you didn't also set something in your launch config to something weird?

**Comment by KytoDragon** [comment]
My launch config:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "${workspaceRoot}/../test.exe",
            "cwd": "${workspaceRoot}/.."
        }
    ]
}

The problem was fixed as soon as I added gdb to my PATH.

**Comment by WebFreak001** [comment]
hm weird, that shouldn't throw an error that i try to do `undefined.toLowerCase()`. I'm gonna check this later
