### ISSUE TITLE
Clicking gear icon brings up launch.json

### ISSUE THREAD

**Issue by DigiAngel** [WebFreak001/code-debug#104]
Topic :)  This is running on Linux if that helps.  Thank you.

**Comment by WebFreak001** [comment]
Thanks for confirming this behaviour. This is indeed what vscode does, seems like everything in order here.

**Comment by DigiAngel** [comment]
So per the docs I don't see this at all:
[https://github.com/WebFreak001/code-debug/blob/master/images/tutorial1.png](url)
Is there something additional I'm supposed to do?

**Comment by WebFreak001** [comment]
You get that if you don't have any configuration yet. You are right about that then, I can update the documentation there.

**Comment by DigiAngel** [comment]
Awesome...thank you!
