### ISSUE TITLE
Support calling GDB over SSH

### ISSUE THREAD

**Issue by bbenoist** [WebFreak001/code-debug#11]
Could it be possible to implement support for calling GDB over SSH ?

From what I've understood, it seems quite easy to implement within code-debug. You would simply need to replace the system executable calls and stdio redirections by an appropriate SSH implementation. [simple-ssh](https://www.npmjs.com/package/simple-ssh) seems to do the job but there might be better alternatives.

You can take a look at the [Visual Studio (!= vscode) GDB Debugger Extension](https://blogs.msdn.microsoft.com/vcblog/2015/11/18/announcing-the-vs-gdb-debugger-extension/) for an example implementation of this use-case. Source code of [Microsoft/MIEngine](https://github.com/Microsoft/MIEngine) might also help :wink: 

Here are my personal requirements for this feature:
* Use either authentication with a password or with an SSH private key file.
* Expose the possibility to use a custom SSH port
* The `target` field must point to the target executable not the ssh server

`launch.json` proposal:
```json
"request": "launch",
"target": "./bin/executable",
"cwd": "/home/target/build",
"ssh": {
  "host": "127.0.0.1",
  "port": "2222",
  "user": "jdoe",
  "password": "pw4jdoe"
}
```

**Comment by WebFreak001** [comment]
Saving a password in clear text is terrible though. This should only allow private key files

**Comment by WebFreak001** [comment]
Maybe "target": "jdoe@127.0.0.1:2222:/home/target/build/bin/executable" instead

**Comment by bbenoist** [comment]
Thanks for the feedback :+1: 

> Saving a password in clear text is terrible though.

Maybe for the most common usages but not when using a [Vagrant](https://www.vagrantup.com/) box whose SSH ports are only exposed to the host system and whose SSH private keys are automatically regenerated :wink: 

> This should only allow private key files

I tend to believe that such decisions should be left to the end-user.

> Maybe "target": "jdoe@127.0.0.1:2222:/home/target/build/bin/executable" instead

If you give me the choice between an option requiring a specific string format and an object consisting of clearly separated options, I would choose the first.

I find it worse that my configuration proposal because it would involve extra considerations which are not actually required. Apart from a debatable removal of extra JSON options (you would still have to specify a private key or password however), I see no obvious reason for creating an extra string format whereas such options would end up being loaded separately in the code.

**Comment by WebFreak001** [comment]
Right, and having children in the json also gives better auto completion for vscode. Might use that then instead

**Comment by bbenoist** [comment]
I forgot an additional requirement. X11 forwarding must be supported (to debug native GUI applications). In that sense, it might be better to use [ssh2](https://www.npmjs.com/package/ssh2) instead of simple-ssh.

**Comment by bbenoist** [comment]
Thanks for the quick implementation :smiley: 

However it does not works with my use-case (Windows vscode connecting to a Linux SSH server).

Debug console output:
```
Running gdb over ssh...
undefined=thread-group-added,id="i1"
Failed to run command `file-exec-and-symbols "\\home\\vagrant\\build-debug\\hello-cxx"`: \home\vagrant\build-debug\hello-cxx: No such file or directory.
An error occured: \home\vagrant\build-debug\hello-cxx: No such file or directory.
```

My `launch.json` configuration:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug",
      "type": "gdb",
      "request": "launch",
      "target": "./bin/hello-cxx",
      "cwd": "${workspaceRoot}",
      "ssh": {
          "host": "127.0.0.1",
          "port": 2222,
          "cwd": "/home/vagrant/build-debug",
          "password": "vagrant",
          "user": "vagrant"
      }
    }
  ]
}
```

It looks likes `/` are being converted to `\` during the process...

**Comment by WebFreak001** [comment]
Should be fixed now

**Comment by bbenoist** [comment]
Nope, same output here.

After a few searches, I fixed the issue by removing lines 53 and 54 of mi2.js:
```typescript
if (!path.isAbsolute(target))
  target = path.join(cwd, target);
```

I now am suffering from similar problems when setting breakpoints:
```
Running gdb over ssh...
undefined=thread-group-added,id="i1"
Running executable
Breakpoints for file Z:\home\vagrant\build-debug\src\main.cxx
Failed to run command `break-insert Z:\home\vagrant\build-debug\src\main.cxx:5`: No source file named Z.
An error occured: No source file named Z.
Hello CXX!
```

**Comment by bbenoist** [comment]
Again, I fixed breakpoint issues by modifying lines which change some filesystem paths.

Ugly fix on line 167 of gdb.ts:

```typescript
  path = this.switchCWD + '/' + path.replace('\\', '/'); // path.resolve(this.switchCWD, path);
```

**Comment by bbenoist** [comment]
A screen capture to show that everything works fine after applying my quick & dirty fixes :tada: :

![image](https://cloud.githubusercontent.com/assets/2091902/12935603/46e903ec-cf97-11e5-8893-43c1112f4636.png)

**Comment by WebFreak001** [comment]
Changed it to a less hacky way with path.posix now. Can you give it a try?

**Comment by bbenoist** [comment]
It's better but still not 100% working.

Here is what I have in-place of the source-file which has a breakpoint:

```
Source z:\src-github\code-debug\z:\src-github\proto\src\main.cxx is not available.
```

Screen capture:

![image](https://cloud.githubusercontent.com/assets/2091902/12942680/27a9741c-cfdd-11e5-885a-cf6a01dde978.png)

Looks like the global posix usage had side-effects...

**Comment by bbenoist** [comment]
The weirdest being that `z:\src-github\code-debug\z:\src-github\proto\src\main.cxx` contains two different directories. The first one only contains the code-debug extension and the second one contains the debugged source code.

I wonder how can it be even possible to have the first one here :scream:

**Comment by bbenoist** [comment]
After a few debugging, I have opened [a PR with the fix for my issue](https://github.com/WebFreak001/code-debug/issues/13).

The problem came from [`path.resolve`](https://nodejs.org/api/path.html#path_path_resolve_from_to) which relied on the POSIX convention whereas it needed the Windows one to translate the path to local.

Regardless of my fix, I believe that the filesystem path management should be clarified by only translating paths where really appropriate (i.e. the closer to extension IOs, the better) and not forcing a global POSIX path convention.
