### ISSUE TITLE
registers are no longer shown in variable list

### ISSUE THREAD

**Issue by mikebenfield** [WebFreak001/code-debug#115]
I installed this extension earlier today and when I used it there was a section under Variables to see General Purpose Registers and another section for the SSE registers. 

Then I closed VS code. Later I went to debug again. Now the register sections are gone. 

See [here](http://imgur.com/a/Tz0n0).

Maybe this isn't a bug and there's some way to make the registers show up again, but I changed nothing.

**Comment by WebFreak001** [comment]
Uh did you stop at a different source position or update the debugger?

**Comment by mikebenfield** [comment]
No. I've tried stopping at other source positions too. This is using lldb-mi, by the way.

**Comment by mikebenfield** [comment]
Sorry, I must have lost my mind. I think I was using a different VS Code debugging extension earlier that let me see registers.

**Comment by WebFreak001** [comment]
Yeah that was really confusing me, I never saw any registers when debugging
