### ISSUE TITLE
Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by faustinoaq** [WebFreak001/code-debug#117]
@WebFreak001 I can't install Native debug extension, just got this error:

![screenshot_20170723_122735](https://user-images.githubusercontent.com/3067335/28501494-5331beb2-6fa2-11e7-975e-03102184a14a.png)

Also I tried to update before but the same happened.

**Comment by WebFreak001** [comment]
if you can't update it's vscode's fault, my extension doesn't have any code run until you reload the window after installing

**Comment by gentoo90** [comment]
Same here. Can't install, can't update. vscode-1.14.2, both linux and windows. Relaunch didn't help.

**Comment by faustinoaq** [comment]
@WebFreak001 But I can install other extension successfully

**Comment by WebFreak001** [comment]
I will try to publish again, maybe something went wrong there

**Comment by gentoo90** [comment]
I was able to successfully install from VSIX downloaded from the market according to this instruction https://gist.github.com/myst729/9ad860b03e1806389ba342961f0f0805

**Comment by gentoo90** [comment]
BTW market says it's version 0.20.0, while github says it's 0.20.1

**Comment by WebFreak001** [comment]
huh how does github say 0.20.1, I never released that version

**Comment by gentoo90** [comment]
Yes, my bad it's 0.21.1

**Comment by faustinoaq** [comment]
@gentoo90 I was able to install this extension cloning the github repo on my extensions folder:

```
cd ~/.vscode/extensions
git clone https://github.com/WebFreak001/code-debug.git
cd code-debug/
npm install
npm run compile
```

**Comment by WebFreak001** [comment]
I released a new version, does it work now? (0.21.2)

**Comment by faustinoaq** [comment]
@WebFreak001 yes, it's working now, What was the problem?

**Comment by WebFreak001** [comment]
maybe the icon using an svg but probably just uploaded them too quickly because I made 2 pushes because I forgot to pull at first

**Comment by faustinoaq** [comment]
just things that happen :sweat_smile: 

Thanks you again!
