### ISSUE TITLE
Call stack is empty after the first breakpoint.

### ISSUE THREAD

**Issue by TheLoneRanger14** [WebFreak001/code-debug#119]
If submitting a bug please make sure

- [ ] If you are using gdb
  - [ ] `gdb --version` >= 7.7.1
  - [ ] it works on the command line with `gdb`
  - [ ] `cwd` and `target` are properly set
- [x]  If you are using lldb
  - [x] `lldb --version` >= 3.7.1
  - [x] it works on the command line with `lldb-mi`
  - [x] `cwd` and `target` are properly set

Screenshots are helpful but not required

I am using lldb on Ubuntu, the first I hit a breakpoint I can see the callstack perfectly, but then I continue and hit another/same breakpoint and the callstack only first/current frame.

`bt` on the Debug Console correctly displays the backtrace.

**Comment by WebFreak001** [comment]
?
