### ISSUE TITLE
Unable to debug in latest release

### ISSUE THREAD

**Issue by csholmq** [WebFreak001/code-debug#12]
![image](https://cloud.githubusercontent.com/assets/1297882/12941478/240ca202-cfd3-11e5-9637-22043c43a063.png)

```
{
	"version": "0.3.1",
	"configurations": [
		{
			"name": "Debug GDB",
			"type": "gdb",
			"request": "attach",
			"target": ":4444",
            "remote": true,
            "autorun": ["-monitor interface=0"]
		}
	]
}
```

**Comment by WebFreak001** [comment]
remove the '-' at the start of the command. If commands are starting with '-' it thinks they are a MI command

**Comment by csholmq** [comment]
Still not working. 

![image](https://cloud.githubusercontent.com/assets/1297882/12947428/89d18e9a-cffb-11e5-8d0f-d60f79eb6f3b.png)

**Comment by WebFreak001** [comment]
Are you running gdbserver on localhost on port 4444?

**Comment by csholmq** [comment]
Yes. That's my GDB bridge which relays to my target over a CAN bus. So when I say it connects, I mean to my GDB bridge running locally on my computer. No monitor commands are patched through (it worked in 0.2.0)

**Comment by WebFreak001** [comment]
your configuration misses `executable` and `cwd`. For me gdbserver works with cwd and executable.

`executable` loads the symbols and `cwd` makes the source paths available

**Comment by csholmq** [comment]
Didn't make a difference. Now says that symbols have been read, but same error.

```
{
	"version": "0.3.1",
	"configurations": [
		{
			"name": "Debug GDB",
			"type": "gdb",
			"request": "attach",
			"target": ":4444",
            "remote": true,
            "autorun": ["monitor interface=0"],
            "executable": "${workspaceRoot}/Sw/A_XMC/out/use/A_Myriad_A_5_6.elf",
            "cwd": "${workspaceRoot}"
		}
	]
}
```

**Comment by WebFreak001** [comment]
What os are you on?

Also im not sure if this is a code-debug issue. Does it work from the console?

**Comment by WebFreak001** [comment]
also i uploaded a new release. You dont need to prefix executable with workspaceRoot anymore.

**Comment by csholmq** [comment]
Updated and reconfigured.

```
{
	"version": "0.3.3",
	"configurations": [
		{
			"name": "Debug GDB",
			"type": "gdb",
			"request": "attach",
			"target": ":4444",
            "remote": true,
            "autorun": ["monitor interface=0"],
            "executable": "../use/A_Myriad_A_5_6.elf",
            "cwd": "${workspaceRoot}/Sw/A_XMC/out/obj"
		}
	]
}
```

![image](https://cloud.githubusercontent.com/assets/1297882/12949320/6a7311a2-d007-11e5-8749-147b2db564f8.png)

**Comment by WebFreak001** [comment]
it will now assume all source code is in /out/obj

I think its a bug with GDB because `cannot execute this command while the target is running` can't possibly be caused by the extension. It happens with GDB in other places too: https://stackoverflow.com/questions/16900615/gdb-step-not-working-as-expected

Does it work if you debug it manually from the console?

**Comment by csholmq** [comment]
Yes, that was my intent. I have my .c/.h/.o in out/obj and my elf file in out/use.

I got it working now but I had to manually run `target remote localhost:4444` which I didn't had to do before.

**Comment by WebFreak001** [comment]
hm, the extension actually calls the MI command of that. See mi2.ts:169

**Comment by csholmq** [comment]
Yes. But it works when my first `autorun `command is `target remote localhost:4444`

**Comment by csholmq** [comment]
Any way to debug which messages are being sent?

**Comment by WebFreak001** [comment]
I can let it print all input to the console

**Comment by csholmq** [comment]
Yeah. Maybe a debug boolean that lets you "debug the debugger" :) :+1:

**Comment by WebFreak001** [comment]
ok there is now an option to print GDB calls

**Comment by csholmq** [comment]
For some reason, it seems to send everything twice...

Note that most of the errors are due to the limited command support of my GDB bridge (failed `stack-list-frames`, etc).

```
monitor port=0
monitor speed=500000
monitor type=0
monitor protocol=0
monitor unit=2
monitor unlockcode=xxx
monitor connect
add-symbol-file C:/dev/xxx/xxx_Myriad/Sw/A_XMC/out/use/A_Myriad_A_5_6.elf 0x8020000
Can't send signals to this remote system.  SIGILL not sent.
target remote localhost:4444
A program is being debugged already.  Kill it? (y or n) [answered Y; input not from terminal]
Cannot execute this command while the target is running.
5-stack-list-frames 0 20
Remote debugging using localhost:4444
0x0000a408 in ?? ()
Not implemented stop reason (assuming exception): undefined
monitor interface=0
monitor port=0
6-stack-list-frames 0 20
monitor speed=500000
monitor type=0
monitor protocol=0
monitor unit=2
monitor unlockcode=xxx
monitor connect
add-symbol-file C:/dev/xxx/xxx_Myriad/Sw/A_XMC/out/use/A_Myriad_A_5_6.elf 0x8020000
add symbol table from file "C:/dev/xxx/xxx_Myriad/Sw/A_XMC/out/use/A_Myriad_A_5_6.elf" at
	.text_addr = 0x8020000
(y or n) [answered Y; input not from terminal]
Reading symbols from C:\dev\xxx\xxx_Myriad\Sw\A_XMC\out\use\A_Myriad_A_5_6.elf...
done.
Failed to run command `stack-list-frames 0 20`: Cannot access memory at address 0xa404
An error occured: Cannot access memory at address 0xa404
Failed to run command `stack-list-frames 0 20`: Cannot access memory at address 0xa404
An error occured: Cannot access memory at address 0xa404
```

**Comment by WebFreak001** [comment]
Im not sure how I can fix that without having such a GDB bridge myself as everything works with gdbserver. Considered forking this project and editing it? All you need to change would be in src/backend/mi2/mi2.ts in function connect: https://github.com/WebFreak001/code-debug/blob/master/src/backend/mi2/mi2.ts#L155-L177

**Comment by csholmq** [comment]
Perhaps this issue should be closed if I'm the only one experiencing this. I could fork and patch to suit my needs, but I wouldn't know if I broke normal debugging for everybody else.

Reopen if somebody else experiences this.
