### ISSUE TITLE
Debugging core dump

### ISSUE THREAD

**Issue by mosolovsa** [WebFreak001/code-debug#121]
Hi! Thanks for the awesome plugin!

Can you please clarify is it possible to debug [core dumps](https://en.wikipedia.org/wiki/Core_dump)?

**Comment by WebFreak001** [comment]
if it's possible with gdb or lldb it should be possible with the extension by passing the correct config arguments or adding it into the extension as extra type. I have never debugged a core dump but if you know a way to do it with gdb/lldb which makes sense in an editor (filename and line number are a must) I could look into it

**Comment by mosolovsa** [comment]
It's a postmortem debugging, unix genetates core dump file (if it size doesn't exceeds limit in os, to turn off limit "ulimit -c unlimited") on a executable crash. You can inspect variables, stack trace and etc.
I've never used it's from gdb because Eclipse IDE with CDT plugin provides GUI for C++, however I want to try it for Rust.
To start debugging core you need 3 things:
1. gdb
2. executable with debugging info
3. core dump
```
gdb [executable with debugging info] [core dump]
```
gdb provides line numbers and filenames, but I'm not sure if it's important. You can't step in/over in core dump debugging, however you can inspect variables just before crash to find the reason of a crash.

Is there a way to provide path to core dump file in plugin?

[Short youtube example](https://www.youtube.com/watch?v=mlfz6c9frSU)

**Comment by WebFreak001** [comment]
Right now you can only do it by either setting the launch mode to attach, setting executable to the correct executable and setting the core dump file as target OR leaving it as launch and adding `"debugger_args": ["executable", "coredump"]`, though I'm not sure if that will succeed

**Comment by mosolovsa** [comment]
I was able to analyse core dump with cfg:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Attach to PID",
            "target": "main",
            "gdbpath": "gdb",
            "cwd": "${workspaceRoot}",
            "debugger_args": [
                "${workspaceRoot}/main", "${workspaceRoot}/core"
            ]
        }
    ]
}
```
![2017-08-25-124211_1920x1056_scrot](https://user-images.githubusercontent.com/15525120/29706411-d5b0b550-8992-11e7-8b82-148b798340c8.png)

Thanks for the clarification and great plugin! Let me know if I can help somehow.
