### ISSUE TITLE
Failed to load MI Debugger: Error: write EPIPE

### ISSUE THREAD

**Issue by JohnKozell** [WebFreak001/code-debug#124]
Should I be able to get GDB 7.6.1 running with VSCode and WebFreak001 0.21.2?
I've installed the extension & GDB (MinGW) and configured a simple launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Debug",
            "target": "test.exe",
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Particle\\Toolchain\\MinGW\\bin\\gdb.exe",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

However, when I start debugging I receive the error:

> Failed to load MI Debugger: Error: write EPIPE

![epipe](https://user-images.githubusercontent.com/7659395/33410981-e244f54c-d550-11e7-8d4b-bc8930492a50.png)

Might this be an issue in my toolchain (like GDB version), or a bad configuration file? 
I just don't know where to narrow the search; I've been beating on this launch.json for hours now.

Thanks

-John

**Comment by WebFreak001** [comment]
I don't know where you got that config from but to change the executable using my extension you need to use `"gdbpath"` instead of `"miDebuggerPath"` and MINode doesn't exist

**Comment by JohnKozell** [comment]
Thank you very much @WebFreak001, this is my config now, and it's starting to work (for the first time):
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Debug",
            "target": "test.exe",
            "gdbpath": "C:\\Particle\\Toolchain\\MinGW\\bin\\gdb.exe",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```
I tried quite a bit of settings combinations and did a lot of web searching, but initially I think I started [HERE](https://code.visualstudio.com/docs/languages/cpp).
I've looked at the readme on this site, and the intro screen on the extension in VSCode, but I don't see gdbpath. Is there a basic reference or simple example I missed somewhere?
Also, what does the EPIPE message mean, and is it possible to have a more descriptive message?
I was also getting a null path error previously, that I figured out was a missing property in the config, but I had to determine by trial and error because it didn't tell me the name of the property.

-John

**Comment by WebFreak001** [comment]
they use the C/C++ extension which can also debug instead of mine. The debug extension api tried to spawn the program but it didn't exist (though that should be ENOENT) so I guess it started something which closed wrongly but idk

**Comment by JohnKozell** [comment]
Thanks again @WebFreak001. I plan on continuing to use your extension (not the C/C++). Just trying to understand, and make your product better and more popular. I offered the reference only to ask if this was a valid reference for webfreak.

**Comment by WebFreak001** [comment]
well my extension was the first gdb extension but if you are on windows I think the C/C++ extension is better because it supports the msvc debugger, I have a few features which are useful for special things such as embedded debugging or remote (not sure on the state on the C/C++ extension there). I also have a special D debugger for windows.
