### ISSUE TITLE
Use with intel's gdb-ia

### ISSUE THREAD

**Issue by rafmudaf** [WebFreak001/code-debug#137]
I'm hoping to use Native Debug with the intel gdb debugger, gdb-ia.

I've created a launch configuration like this
```
{
            "name": "Debug",
            "type": "gdb",
            "printCalls": true,
            "valuesFormatting": "disabled",
            "showDevDebugOutput": true,
            "terminal": "internalConsole",
            "gdbpath": "gdb-ia",
            "request": "launch",
            "target": "build/modules-local/beamdyn/beamdyn_driver",
            "cwd": "${workspaceRoot}",
        }  
```

I can debug this executable on the command line with gdb-ia, but Native Debug hangs on execution. I've cloned the code for the extension and set up a debug version of it to try to find the cause. Having made very little progress, any guidance would be helpful.

![screen shot 2018-03-19 at 1 52 12 pm](https://user-images.githubusercontent.com/13797903/37618729-cc3dbcca-2b7c-11e8-8425-0ad86c1244d2.png)

**Comment by WebFreak001** [comment]
try launching it with `gdb-ia --interpreter=mi2` and check if MI commands work (https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html), start by running the commands you see there in the debug console.

**Comment by rafmudaf** [comment]
@WebFreak001 Thanks for the response. On the command line with gdb-ia, none of the commands in the VSCode debug console work. However, I've replaced them with these working commands:
```
gdb-set target-async on -> set target-async on
environment-directory -> dir
file-exec-and-symbols -> file
exec-arguments -> set args
```
Now it hangs after the fourth command. Is the next command in the sequence `run`?

![screen shot 2018-03-20 at 12 52 58 pm](https://user-images.githubusercontent.com/13797903/37676483-a78c839a-2c3d-11e8-9944-164bba779857.png)

**Comment by WebFreak001** [comment]
uh well the point of MI is to have a machine interface not impacted by locale and with a consistent output and input format. What do these commands return on the command line? It should print them in the vscode console because you enabled `showDevDebugOutput` but as it doesn't it seems like there is a problem. Maybe flushing after each command will help here?

**Comment by WebFreak001** [comment]
About the run command, see Program Execution in the MI docs: https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Program-Execution.html#GDB_002fMI-Program-Execution

**Comment by rafmudaf** [comment]
For reference, this is the output of those commands on the command line: ```
mbp@~/Development/sqrt/build: gdb-ia --interpreter=mi2 sqrt 
=thread-group-added,id="i1"
~"GNU gdb (GDB) 7.12-18.0.760\n"
~"Copyright (C) 2016 Free Software Foundation, Inc; (C) 2017 Intel Corp.\n"
~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
~"This GDB was configured as \"x86_64-apple-darwin15.6.0\".\nType \"show configuration\" for configuration details."
~"\nFor information about how to find Technical Support, Product Updates,              \nUser Forums, FAQs, tips and tricks, and other support information, please visit:\n"
~"<http://www.intel.com/software/products/support/>.For help, type \"help\".\n"
~"Type \"apropos word\" to search for commands related to \"word\"...\n"
=cmd-param-changed,param="args",value="bd_driver.inp"
~"Reading symbols from sqrt..."
~"Reading symbols from /Users/rmudafor/Development/sqrt/build/sqrt.dSYM/Contents/Resources/DWARF/sqrt..."
~"done.\n"
~"done.\n"
(gdb) 
set target-async on
&"set target-async on\n"
=cmd-param-changed,param="mi-async",value="on"
^done
(gdb) 
dir "/Users/rmudafor/Development/sqrt"
&"dir \"/Users/rmudafor/Development/sqrt\"\n"
~"Source directories searched: /Users/rmudafor/Development/sqrt:$cdir:$cwd\n"
^done
(gdb) 
file "/Users/rmudafor/Development/sqrt/build/sqrt"
&"file \"/Users/rmudafor/Development/sqrt/build/sqrt\"\n"
~"Reading symbols from /Users/rmudafor/Development/sqrt/build/sqrt..."
~"Reading symbols from /Users/rmudafor/Development/sqrt/build/sqrt.dSYM/Contents/Resources/DWARF/sqrt..."
~"done.\n"
~"done.\n"
^done
(gdb) 
set args 4
&"set args 4\n"
=cmd-param-changed,param="args",value="4"
^done
(gdb) 
```

However, I stashed the changes I had made to Native Debug and started over. Removing ` "terminal": "internalConsole",` from the launch config solved the problem!

So my launch.settings is/are now
```
{
    "name": "Debug",
    "type": "gdb",
    "request": "launch",
    "printCalls": true,
    "valuesFormatting": "disabled",
    "showDevDebugOutput": true,
    // "terminal": "internalConsole",
    "gdbpath": "gdb-ia",
    "target": "build/sqrt",
    "cwd": "${workspaceFolder}",
    "arguments": "4",
}
```

**Comment by rafmudaf** [comment]
@WebFreak001 is this expected with `"terminal": "internalConsole"`? Would you like me to open an issue for that or just close this one?

**Comment by WebFreak001** [comment]
uhh what's internalConsole? don't even support that

**Comment by rafmudaf** [comment]
I assume that refers to the "debug console" in vscode, https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes
