### ISSUE TITLE
README.md images are broken

### ISSUE THREAD

**Issue by bbenoist** [WebFreak001/code-debug#14]
Il looks like `README.md` images URLs from your website are broken.

![image](https://cloud.githubusercontent.com/assets/2091902/12944830/f86911b4-cfe9-11e5-8fc2-d94a78f719ff.png)

Relying on external sources makes the content your Git commits dependent of those sources. This implies a lot of considerations such as high-availability and concurrent version management.

As an example, it is impossible for contributors to update screen captures without access on i.webfreak.org.

IMO, you should directly add them into your repository and use relative URLs to display their content in the `README.md` file.

It does not breaks the page displayed on the marketplace.

For a real-world example, see:
* https://raw.githubusercontent.com/bbenoist/vscode-qml/master/README.md
* https://github.com/bbenoist/vscode-qml/blob/master/README.md
* https://marketplace.visualstudio.com/items?itemName=bbenoist.qml

**Comment by csholmq** [comment]
Utilizing Githubs cloud service should work as well. E.g. dragging and dropping an image into the comment window will also upload the image.

E.g. https://cloud.githubusercontent.com/assets/1297882/12945747/cd7b2888-cfef-11e5-8202-32919b248ee4.gif

**Comment by bbenoist** [comment]
> Utilizing Githubs cloud service should work as well. E.g. dragging and dropping an image into the comment window will also upload the image.
>
> E.g. https://cloud.githubusercontent.com/assets/1297882/12945747/cd7b2888-cfef-11e5-8202-32919b248ee4.gif

[Related tutorial](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/)

Although they are binary files, I tend to prefer indexing images directly in the Git repo.

This because relying on an external link supposes you have a working internet connection. Which might not be true when reading the documentation from a local repository clone (coding while traveling is a good use-case).

Moreover, it also involves extra-work when both coding (upload the image and copy-paste the corresponding URL to update any reference of the previous one) and reviewing PRs (modified images will not be displayed in the "Files changed" tab and URLs would have to be copied-pasted to a web browser address bar).

Also, by relying on GitHub URLs within your source code, you introduce a strong dependency to this specific source-code hosting service. Thus, complicating migration to other services such as GitLab, Bitbucket and on-premises solutions like GitHub Enterprise.

Finally, we have no guarantee that GitHub attachments will be kept forever. As an example I am regularly frustrated by broken imgur (reddit image CDN) urls when clicking on an old reddit link

![image](https://cloud.githubusercontent.com/assets/2091902/12946528/7b406eb0-cff5-11e5-8200-ed4f9655b042.png)
