### ISSUE TITLE
Code-Debug(GDB) no longer stop when program asks for input, but there's no input

### ISSUE THREAD

**Issue by ZZYSonny** [WebFreak001/code-debug#141]
Both my windows and mac have the problem.
![image](https://user-images.githubusercontent.com/28442838/37835200-9500bec6-2eea-11e8-9a1c-053c03dcd1dd.png)
In this situation, the program wants to read number for n. But I didn't write anything into the debug terminal. So instead of stopping at that scanf line and wait for input like it did in 0.21.0, code-debug just skip it. And after that, some strange value is given. (Causing my later part to RE)
However, everything is right when I've put freopen at the beginning and prepare for the input.

**Comment by WebFreak001** [comment]
uh wow this shouldn't happen, nothing even changed there, what's the input if you read a string `%s`?

**Comment by ZZYSonny** [comment]
![image](https://user-images.githubusercontent.com/28442838/37842034-0b19637c-2efc-11e8-8100-0e3c65825204.png)
It is still some strange things

**Comment by WebFreak001** [comment]
that's a command the extension sends, I will look into it

**Comment by LeszekSwirski** [comment]
Looks like a weird interaction between gdb async and programs reading stdin maybe?

**Comment by WebFreak001** [comment]
well it should never write to the process stdin because of the special prefixes though, but that could be it

**Comment by LeszekSwirski** [comment]
Maybe there's some unlucky stdin flushing?

**Comment by alianZhen** [comment]
It seems need set terminal argument like this `"terminal": ""`.And then it can run in console

**Comment by GitMensch** [comment]
this is actually the same issue as #262, closing it in favor of it as it contains the "technical reasons for it". And yes: as long as the terminal gets an own pty instead of using GDB console everything works as expected (my personal preference would be to have all program input/output in a new "Terminal" within vscode _be default_).
