### ISSUE TITLE
Complex data types aren't supported

### ISSUE THREAD

**Issue by Yanpas** [WebFreak001/code-debug#148]
If submitting a bug please make sure

- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1
  - [x] it works on the command line with `gdb`
  - [x] `cwd` and `target` are properly set

here is a list of local variables:

![image](https://user-images.githubusercontent.com/7345761/42169925-c807c3b4-7e1d-11e8-9fc5-3dbfac06eb08.png)

Here is a code: `std::vector<std::string> aa{"a", "bbb", ""};`

As you see `aa` isn't pretty expanded

**Comment by WebFreak001** [comment]
Can you try all different values of the `"valuesFormatting"` setting to see which one works best?

**Comment by Yanpas** [comment]
Didn't know about that. I've tried `prettyPrinters` and it seems to works fine. Maybe it should be default for gdb?

**Comment by WebFreak001** [comment]
depending on the language some of them work and some of them don't. The current default always produces at least some kind of usable output.

**Comment by Yanpas** [comment]
As an option the generator for `launch.json` may add `"valuesFormatting": "parseText"` by default.

**Comment by WebFreak001** [comment]
yeah that could be a good idea
