### ISSUE TITLE
how to remote debug

### ISSUE THREAD

**Issue by ghost** [WebFreak001/code-debug#152]
Hello

I want to setup "remote debug" on VS Code (pc host) with my target device (embedded linux). On target side the gdbserver, gcc, ssh runs. how is it possible to set up remote dubugging over SSH? and it include remote compilation on target with gcc (sources are dowloaded to target)?

Thanks

**Comment by WebFreak001** [comment]
hi, have you tried the templates that are bundled with code-debug? Just ctrl-space in your configurations block.

With the extension you can either debug via SSH which will connect and run the `gdb` command on the server (Autocomplete: GDB: Launch over SSH)

or you can connect to a gdbserver running on the target device if the port is forwarded. (Autocomplete: GDB: Connect to gdbserver)

You can't run gdbserver over ssh by starting debugging through code-debug though, you would have to start it manually first. You could add a task which is run before debugging though which makes sure that the gdb server is running. For that use the vscode tasks.

**Comment by GitMensch** [comment]
Closed because the question was solved (and this scenario is also described in the README).
