### ISSUE TITLE
autorun need run one by one, not same time

### ISSUE THREAD

**Issue by GongT** [WebFreak001/code-debug#153]
I'm using this extension to debug a remote program (a chip with openocd).

my autorun: 
* interrupt
* load
* break main
* c

It seems to run sametime, `continue` not wait `load` to finish.

**Comment by WebFreak001** [comment]
it would add a lot of complexity just for having two cases with the current async code there, how about creating a GDB python function instead which runs all your commands in order? (`gdb.execute` in python) using `python execfile ("script-name")` or for a quick and simple hack:
```
python for cmd in ["interrupt", "load", "break main", "c"]: gdb.execute(cmd)
```

**Comment by GongT** [comment]
OMG, I never imagine there is a command named "python" in gdb...

Thank you!!

**Comment by GongT** [comment]
well.... code being escaped...
```
  File "<string>", line 1
    autorun = [\'delete breakpoints\', \'delete tracepoints\', \'load\', \'c\']
```

**Comment by GongT** [comment]
If I write python single line:
```
4-break-delete
5-interpreter-exec console python for cmd in [\'delete breakpoints\', \'delete tracepoints\', \'load\', \'c\']: gdb.execute(cmd)
6-thread-info
4^done
(gdb)
~">"
~">"

7-break-insert -f "/data/DevelopmentRoot/canaan-creative/cpp-test/yes/main.c:37"
8-break-insert -f "/data/DevelopmentRoot/canaan-creative/cpp-test/yes/main.c:50"
~">"

~">"

9-thread-info
~">"
```

python always wait for input.

**Comment by WebFreak001** [comment]
opened or closed?

**Comment by GongT** [comment]
closed, LOL

**Comment by WebFreak001** [comment]
mind commenting what was broken and how you fixed it in case for future readers? :)

**Comment by GongT** [comment]
Never mind, It's my mistake.

using "python" command solved my problem...
