### ISSUE TITLE
Connection thru docker like ssh

### ISSUE THREAD

**Issue by bruegth** [WebFreak001/code-debug#155]
Please add a option to connect via docker client:
e.g.: 
docker --tls -H docker_daemon_hostname:2376 exec -i name_of_docker_container lldb-3.9 -O "settings set target.exec-search-paths ...

**Comment by GitMensch** [comment]
What was your solution?

**Comment by bruegth** [comment]
For Windows:

"version": "0.2.0",
"configurations": [
	{
		"name": "Attach to process on ServerX",
		"type": "coreclr",
		"request": "attach",
		"processId": "1",
		"pipeTransport": {
			"pipeCwd": "${workspaceRoot}",
			"pipeProgram": "\"C:\\Program Files\\Docker\\Docker\\resources\\bin\\Docker.exe\"",
			"pipeArgs": ["--tls", "--tlscacert=\"${env:AppData}\\Docker\\certs.d\\ca.pem\"", "--tlscert=\"${env:AppData}\\Docker\\certs.d\\cert.pem\"", "--tlskey=\"${env:AppData}\\Docker\\certs.d\\key.pem\"", "-H", "ServerX:2376", "exec", "-i", "container_name"],
			"debuggerPath": "/vsdbg/vsdbg",
			"quoteArgs": false
		}
	},
