### ISSUE TITLE
A new setup for remote linux device

### ISSUE THREAD

**Issue by ghost** [WebFreak001/code-debug#163]
Hello,

I have my remote device as "user: root" with none password at "192.168.15.124" and want to configure remote debug. I wonder if `host` means remote device?
Regarding forwardX11 what needs to run on remote device to have forwardX11 since I run my own flavor of embedded-linux.   and what to run on host-side on PC where I want to access and debug code from.

I am trying to configure this way ...

```
"request": "launch",
"target": "./executable",
"cwd": "${workspaceRoot}",
"ssh": {
	"forwardX11": true,
	"host": "192.168.15.124",
	"cwd": "/home/root/project/",
	"keyfile": "/path/to/.ssh/key", // OR
	"password": "",
	"user": "root",
	"x11host": "localhost",
	"x11port": 6000,
	// Optional, content will be executed on the SSH host before the debugger call.
	"bootstrap": "source /home/remoteUser/some-env"
}
```

**Comment by WebFreak001** [comment]
X11 forwarding uses the default SSH forwarding capabilities. So if you are running OpenSSH you should have it. Your client PC where you start debugging is what needs to support remote X11 connections (which is x11host and x11port)

If you provide both keyfile and password it is undefined which one it will pick, also that keyfile probably does not exist on your PC so you should remove that config entry. Same as the bootstrap config entry.

**Comment by peter73421** [comment]
Thank you. Still I have some problems to run this. I'll do have "hello" program compiled on target side `gcc main.c -Wall -g -o hello` 
Should I run gdbserver on target side `gdbserver localhost:2000 hello` and after start debugging but this procedure is not working... Assume vscode extension runs local gdb. 

How should it be done correctly?

**Comment by peter73421** [comment]
I need to somehow configure gdb ... since I need to use for remote aarch64 device the `gdb-multiarch`

**Comment by GitMensch** [comment]
To configure gdb path: use `gdbpath` which then allows you to "attach" to an empty pid via setup; have gdbserver running on the remote [but without the `localhost`part`]; using `target extended-remote yourserver:yourgdbport` in the `autorun` command. If the source is not on the same place: use `pathSubstitutions`.

As an alternative which does not need GDB at all: use `ssh`configuration, this way GDB is actually started on the remote host, but you need SSH connection details (preferably via key, not via password) in the launch configuration.

... and now, as the Ghost can check for the answer -> closed
