### ISSUE TITLE
Using a GDB command file

### ISSUE THREAD

**Issue by MabezDev** [WebFreak001/code-debug#165]
Hi,

I'm working on an embedded Rust project, I have a gdb command file which works with `cargo run` which handles to connection to the remote, setting key breakpoints etc. I'd like to use this with vscode, I've tried something like this:

```
{
            "type": "gdb",
            "request": "launch",
            "name": "Debug",
            "debugger_args": [
                "-x openocd.gdb"
            ],
            "target": "./target/thumbv7em-none-eabi/debug/mabez_watch",
            "cwd": "${workspaceRoot}"
 },
```

and a few different attempts with various configurations but no luck so far.

Any ideas?

Thanks

**Comment by WebFreak001** [comment]
I have never used gdb scripts in files but you could try

```
	"autorun": ["source openocd.gdb"]
```

Everything in autorun will be run before starting to debug as if the user typed it into the debug console window. https://github.com/WebFreak001/code-debug/blob/606a25b38cdfce33a5f4b7ef7dbcfc0836d21a4a/src/gdb.ts#L97-L100

**Comment by MabezDev** [comment]
That did the trick, thanks!
