### ISSUE TITLE
Possibility to use .gdbinit as debugging setup

### ISSUE THREAD

**Issue by omicronns** [WebFreak001/code-debug#168]
Is it possible to allow extension to just run gdb, so user can setup debugging session via .gdbinit file? Something like:
```
{
    "name": "Debug",
    "type": "gdb",
    "request": "indep",
    "cwd": "${workspaceRoot}",
    "gdbpath": "arm-linux-gnueabihf-gdb"
}
```

**Comment by WebFreak001** [comment]
like #165 ?

**Comment by omicronns** [comment]
Yes, something similar, but I don't want to provide target path in launch.json, and when this property is missing from launch.json it yields an error.

**Comment by WebFreak001** [comment]
what you just have to add `"autorun": ["source path/to/.gdbinit"]`

**Comment by omicronns** [comment]
I can't specify "target" property since binary resides on remote, and it's mandatory.

**Comment by WebFreak001** [comment]
the autorun setting is available in attach and in launch. I have no idea what the `indep` one is you have and I don't support that. Are you posting this issue in the wrong repo?

**Comment by omicronns** [comment]
Thanks.
