### ISSUE TITLE
Failed to get Stack Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by JohnSchooling** [WebFreak001/code-debug#175]
webfreak.debug-0.23.0\out\src\backend\mi2\mi2.js:getStack
v0.22.0 does not have this issue.
Caused by https://github.com/WebFreak001/code-debug/commit/1f4333e5db0e4601a839f30f10ab9bb33f8231b7

Windows 10
GNU gdb (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 8.0.50.20171128-git

After an SVC 0, gdb returns:
file = undefined
func = &lt;signal handler called&gt;

This breaks nativePath.normalize(file) at line 628 with:
Failed to get Stack Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

I have added a comment here: https://github.com/WebFreak001/code-debug/commit/1f4333e5db0e4601a839f30f10ab9bb33f8231b7#commitcomment-32984551

C:\Users\<username>\.vscode\extensions\webfreak.debug-0.23.0\out\src\backend\mi2\mi2.js:getStack
<snip>
625
```
                // if func == <signal handler called> then file is undefined.
                // Causes normalize to fail.
                if (typeof file !== 'undefined') {
                    if (this.isSSH)
                        file = path_1.posix.normalize(file);
                    else
                        file = nativePath.normalize(file);
                }
```
<snip>

Thanks.

**Comment by malte-v** [comment]
I'm getting this error in 0.24.0. This is my `launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Rust",
            "type": "gdb",
            "request": "launch",
            "target": "target/debug/redis-test",
            "valuesFormatting": "parseText"
        }
    ]
}
```

**Comment by WebFreak001** [comment]
can you check the developer tools for a stacktrace? Also best make a separate bug then because it's gonna be a different part of the code than described in this issue

**Comment by malte-v** [comment]
@WebFreak001 Done. #208
