### ISSUE TITLE
Debugging Extension

### ISSUE THREAD

**Issue by marekzmyslowski** [WebFreak001/code-debug#176]
Hello,

I'm trying to debug the extension but I have a problem with the breakpoints. Some of them are working some not. Here are the examples:
1. extension.ts:line 9 works.
2. mi2.ts:line 128 (the error message about the ssh key) doesn't. The message is displayed but the vscode doesn't stop there.
Any advice what can be wrong?

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
npm: 6.9.0

**Comment by WebFreak001** [comment]
debugging extension run on a separate process in vscode, so you can't debug them using the extension debugger directly. I always just send print calls instead of having breakpoints and didn't really look into any other way
