### ISSUE TITLE
Disconnect from attached running process 

### ISSUE THREAD

**Issue by kagonzalez** [WebFreak001/code-debug#184]
Hello, I am working on an Visual Studio Code extension where I need to disconnect from the debugging session before the debugging process has finished and I need to do it from within my extension. I was trying to find how to do this by reading this extension's code, however I couldn't find where you contributed the disconnect button when debugging remotely, no was I sure what you exactly call to disconnect. The closest I got was the disconnectRequest function, however I cant find where it gets called. Anyways, my question for you is how can I request the debugger to disconnect from my code?

Edit: Also, how is it that you guys completely change the debug toolbar to have totally different buttons?

**Comment by WebFreak001** [comment]
just click the stop button, vscode makes it behave differently if the request type is "attach" so it will call disconnect

The toolbar only has what vscode provides, we can't customize that, there is just features you can enable to show some additional built-in buttons like stepping back/running backwards

**Comment by GitMensch** [comment]
Just rechecked: you could just send a direct `detach` via the debugger console (also possible via extension).

@WebFreak001 as the original question was answered a year ago and @kagonzalez seems to be fine with it, can I suggest to close this question-issue?
