### ISSUE TITLE
Thread names in the Call Stack section

### ISSUE THREAD

**Issue by pho** [WebFreak001/code-debug#193]
Hi, I'm developing a FreeRTOS project, where I have a lot of tasks running which gdb shows as threads, and I find myself having to check manually the `info thread` to know which thread I want to expand in the Call Stack box

![image](https://user-images.githubusercontent.com/88469/67019590-32221f80-f0fd-11e9-814c-5a4f038e8b71.png)

It could be great if the Call Stack box would show the thread names too

**Comment by konradsa** [comment]
Second this request, this would be a good feature to have.

**Comment by oltolm** [comment]
I implemented it in https://github.com/WebFreak001/code-debug/commit/be19c277870e04469347bc2f7032af9dd2daf580.
