### ISSUE TITLE
Do we have plan for licensing this project?

### ISSUE THREAD

**Issue by a1994846931931** [WebFreak001/code-debug#198]

**Comment by WebFreak001** [comment]
it's already unlicense / public domain

-> use it however you want, commercially or non-commercially in any way with or without attribution as you want

**Comment by a1994846931931** [comment]
@WebFreak001 No, it's our company's rule that we can't use it unless it's licensed. If you are willing to distribute it freely, may you license it under a permissive license like MIT or BSD? It would be very helpful. Thank you very much!

**Comment by WebFreak001** [comment]
unlicense is a license, check it out here: https://choosealicense.com/licenses/unlicense/

**Comment by a1994846931931** [comment]
@WebFreak001 Thank you so much for the information, it's really helpful!

By the way, do you have any plan for fixing this issue: https://github.com/WebFreak001/code-debug/issues/75? I found it has been up there for over 3 years.

**Comment by WebFreak001** [comment]
currently no real capacity on my side, but I will review and merge PRs.

as a side note, it's possible to spawn programs in a separate terminal for standard input/output on Linux, Mac and Windows. See the `"terminal"` option in the launch config.
