### ISSUE TITLE
consider using query instead of fragment

### ISSUE THREAD

**Issue by akosyakov** [WebFreak001/code-debug#199]
Hi 👋 We are trying to run this extension in Theia: https://github.com/eclipse-theia/theia/issues/6763

And stumbled over the issue that `TextDocumentContentProvider` rely on URI fragment. Theia separates a fragment from URI to adhere to https://tools.ietf.org/html/rfc3986#section-3.5 and avoid duplicate content resolution and editors:
> As such, the fragment identifier is not used in the scheme-specific processing of a URI; instead, the fragment identifier is separated from the rest of the URI prior to a dereference, and thus the identifying information within the fragment itself is dereferenced solely by the user agent, regardless of the URI scheme.

Would you consider to use `query` instead of `fragment`? Query is schema specific and can be used to resolve different content.

**Comment by WebFreak001** [comment]
good point, not quite sure why I even put it in fragment instead of query because I implemented full query argument parsing for it
