### ISSUE TITLE
Publish a new release with the latest changes

### ISSUE THREAD

**Issue by bbenoist** [WebFreak001/code-debug#20]
Hi,
Some people I know would like to use some of the changes you merged yesterday.
Could you please `vsce publish` a new version?

**Comment by Skippz88** [comment]
> Hi,
> Some people I know would like to use some of the changes you merged yesterday.
> Could you please `vsce publish` a new version?
> 

ca6b59353d1ba97507a7ff32fe1dbbd6b0d0056c https ca6b59353d1ba97507a7ff32fe1dbbd6b0d0056c
