### ISSUE TITLE
How I can configure for Pascal debugger in vscode?

### ISSUE THREAD

**Issue by Noboroto** [WebFreak001/code-debug#209]
I have searched on the Internet for a long time but I don't have any way to debug file .exe from Free Pascal compiler with your extension (Native Debug) on Visual Studio Code. Could you give me a tutorial?
I use Windows 10 64 bit build 18362.657 version 1903
FPC 3.0.4, VSCode 1.42.1
my build tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "PAS build active file",
            "command": "fpc",
            "args": [
                "${file}"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by WebFreak001** [comment]
you need a debugger which supports the [GDB MI](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html) interface if you want to use other debuggers than gdb or lldb

otherwise my extension won't support your use-case
