### ISSUE TITLE
failed to debug dlang app

### ISSUE THREAD

**Issue by JunfengJia** [WebFreak001/code-debug#21]
f5 ->

Failed to run command `break-insert /home/aaa/src/d/DCD/src/client/client.d:39`: No source file named /home/aaa/src/d/DCD/src/client/client.d(this file exist actually).

{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug",
			"type": "gdb",
			"request": "launch",
			"target": "./dcd-client",
			"cwd": "${workspaceRoot}"
		}
	]
}

**Comment by WebFreak001** [comment]
is dcd-client existent in the workspace root folder and is all source in the workspace root folder?

**Comment by JunfengJia** [comment]
/home/aaa/src/d/DCD/dcd-client exist, and run directly without pause, because break-insert failed.

**Comment by WebFreak001** [comment]
did you compile with debug information?

**Comment by JunfengJia** [comment]
yes, objdump --syms output symbols. I guess we hit the issue with d and gdb?

**Comment by WebFreak001** [comment]
does adding breakpoints with `gdb ./dcd-client` work? (Please exactly that command, thats the path you also specified in the config)

**Comment by JunfengJia** [comment]
I found the problem, dub doesn't use the copy under DCD project, it will download all packages into it's only cache, thanks for help.
