### ISSUE TITLE
Compiling for armhf

### ISSUE THREAD

**Issue by MGlolenstine** [WebFreak001/code-debug#211]
I'm trying to compile Rust for an embedded armhf device, but I'm unsure on how to do that without having to build it manually.

I wanted to ask if there was a property similar to "bootstrap", that's used to execute ssh commands before executing the program, but it would instead run the commands on the local computer, just so I could set up the local compilation and sending the final binary to the remote device.

**Comment by WebFreak001** [comment]
use preLaunchTask, see https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes
