### ISSUE TITLE
Why log is send to debug console as stderr?

### ISSUE THREAD

**Issue by a1994846931931** [WebFreak001/code-debug#217]
If submitting a bug please make sure

- [ ] If you are using gdb
  - [ ] `gdb --version` >= 7.7.1
  - [ ] it works on the command line with `gdb`
  - [ ] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Relevant code:
https://github.com/WebFreak001/code-debug/blob/5ac331e7b1e809a47de94fbbfdf389287dba7803/src/mibase.ts#L110

Is it intended?

I understand that `log-stream-output` should be treated as an error log, but then it should be converted to `stderr` type before sending it to the log function.

**Comment by WebFreak001** [comment]
category can be one of "console", "stdout", "stderr", "telemetry"

it's stderr so it's printed in red color in vscode, so you know it's probably not part of the program output.
