### ISSUE TITLE
args not available?

### ISSUE THREAD

**Issue by mbristol78** [WebFreak001/code-debug#219]
I have a launch.json that looks like 
		
		{
			"type": "gdb",
			"request": "launch",
			"name": "GDB stuff",
			"target": "/root/work/stuff",
			// "args": ["1"],
			"cwd": "${workspaceRoot}",
			"valuesFormatting": "parseText"
		},

but as you can see "args" is commented out as it is not recognized otherwise.
Is there a way to pass arguments with this settings?

Using;

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git

VScode:
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-13T14:40:29.529Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic snap

If submitting a bug please make sure

- [ ] If you are using gdb
  - [ ] `gdb --version` >= 7.7.1
  - [ ] it works on the command line with `gdb`
  - [ ] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by WebFreak001** [comment]
arguments: string - Arguments to append after the executable (so executable arguments, works like a shell script and I think this can even do piping and stuff like that)

debugger_args: string[] - Additional arguments to pass to GDB (verbose, disable gdbinit, etc.)

**Comment by mbristol78** [comment]
Hi, Thanks for your reply.
Sorry this doesnt work for me

If i try
"target": "/root/work/stuff -exec-arguments 1",
I have the message
Failed to load MI Debugger: /root/work/stuff -exec-arguments 1: No such file or directory. (from file-exec-and-symbols "/root/work/stuff -exec-arguments 1")

Using gdb in shell, I do 
gdb --args /root/work/stuff 1
To get it to work. 
But if i try
"target": "--args /root/work/stuff 1",
I have the same error message.

**Comment by WebFreak001** [comment]
no, arguments is a property in the launch settings. Try checking out all the properties that exist through auto completion

**Comment by mbristol78** [comment]
oh i see ok, thank you. Sorry for my lack of research. Thanks
