### ISSUE TITLE
gdb over ssh, break-insert is not work

### ISSUE THREAD

**Issue by hardboydu** [WebFreak001/code-debug#22]
-----code

```c++
#include <stdio.h>
#include <unistd.h>

int func ( void )
{
    return 0 ;
}

int main ( int argc ,char *argv[] )
{
    int a = 0 ;
    printf ( "hello world\n" ) ;
    return 0 ;
}
```

----- log

```
Running gdb over ssh...
undefined=thread-group-added,id="i1"
Running executable

Failed to run command `break-insert /root/duxin/project/gdbtest/main.cpp:6`: Cannot access memory at address 0x4005a4
An error occured: Cannot access memory at address 0x4005a4

hello world
```

----- launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "./main",
            "cwd": "${workspaceRoot}",
            "ssh": {
                "forwardX11": false,
                "host": "192.168.4.32",
                "cwd": "/root/duxin/project/gdbtest",
                "password": "oracle",
                "user": "root"
            }
        }
    ]
}
```

**Comment by WebFreak001** [comment]
can you add breakpoints when hitting pause first?

**Comment by hardboydu** [comment]
![default](https://cloud.githubusercontent.com/assets/4214337/13063999/23d0f620-d489-11e5-9c8c-54ed79d3ad59.png)

My running environment as follows

Project directory on a Linux machine, by mapping samba to windows, use VSCode open this directory

OS version RHEL 6.3

GDB version info

```bash
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-56.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
```

Compile command

```bash
g++ -g -o main main.cpp
```

**Comment by WebFreak001** [comment]
https://stackoverflow.com/questions/3649468/setting-breakpoint-in-gdb-where-the-function-returns

Seems to be a GDB bug, try putting the breakpoint one line above

**Comment by hardboydu** [comment]
![default](https://cloud.githubusercontent.com/assets/4214337/13096960/55746304-d558-11e5-86a0-95733cec3582.png)

it can work.

**Comment by WebFreak001** [comment]
is the most recent version with the same code compiled on the other side?

**Comment by WebFreak001** [comment]
Some additions were made, does it work now?

**Comment by hardboydu** [comment]
yes, it can work

but,now “target” set relative path is not work, like this "target": "./gdbtest"

“target” set absolute path is ok, like this "target": "/home/xxx/gdbtest/gdbtest"

**Comment by WebFreak001** [comment]
oh yes I think that bug got introduced in the last version because I needed to change some things how LLDB works because it doesn't have the cd command
