### ISSUE TITLE
0.3.6 debug failed

### ISSUE THREAD

**Issue by fyyxxm** [WebFreak001/code-debug#226]
VScosde：v1.45
Cortex-Debug：v0.3.6

![cotex](https://user-images.githubusercontent.com/50574073/81637410-d298b200-9448-11ea-9733-7f6821df89e3.png)

Problem：When debugging ，the page will always be stuck here all the time，Unable to enter the debug page。

but 0.3.5 is OK！

**Comment by WebFreak001** [comment]
wrong repository

https://github.com/Marus/cortex-debug
