### ISSUE TITLE
When I run, the program just seems to exit quietly at assert. No info from gdb.  Stops fine from command line.

### ISSUE THREAD

**Issue by cjolivier01** [WebFreak001/code-debug#228]
If submitting a bug please make sure

```json
        {
            "type": "gdb",
            "request": "launch",
            "name": "GDB (PYTHON) CURRENT FILE",
            "target": "${workspaceRoot}/toolchain/rootfs-x86_64/usr/bin/python",
            "arguments": "${file}",
            "cwd": "${workspaceRoot}/",
            "env": {
            "valuesFormatting": "parseText",
        },
```

- [ X] If you are using gdb
  - [X ] `gdb --version` >= 7.7.1
  - [X ] it works on the command line with `gdb`
  - [ X] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by WebFreak001** [comment]
How are you calling your script through GDB on the command line? I would assume from your launch config with "exit quietly at assert" you mean you have an assert in your python code? In this case do python assertions even trigger GDB?

**Comment by cjolivier01** [comment]
it works ok and strops as it should in gdb form command line. 
gdb python
r <my script>

asserts trigger gdb with SIGABORT (or whatever that signal is).

I am doing the same thing with the launch.json. 

What other settings are set behind the scenes in gdb that I can try on command line to see if it does the same thing? it would help to be able to reproduce the problem on the command line.

Also, how do I set up environment to edit the plugin source and use it in vscode? so I link 'out' dir in extensions to source or do I have to go through full install, etc?

**Comment by WebFreak001** [comment]
add `"printCalls": true, "showDevDebugOutput": true` to your launch config to see what GDB commands it passes.

To work on the extension, first
`ln -s /absolute/path/to/checked-out/code-debug ~/.vscode/extensions` (path may differ)
to make it reload the extension on every window reload.

To change source code, first do `npm install` then edit the .ts files and run `tsc` to compile once or just start `tsc -w` to let it compile in the background while you are editing.

**Comment by cjolivier01** [comment]
ok that didnt help, process just exists.. its not even hitting an assert now, it just stops debugging. no clue why. ive seen this befpore in other situations. its one of the reasons I went back to clion but Id like to switch back to vscode because clion has huge issues with big projects...

**Comment by WebFreak001** [comment]
I would try an extension specially designed for debugging python instead. I have never used GDB to debug python before so I can't really help with it.

**Comment by cjolivier01** [comment]
> I would try an extension specially designed for debugging python instead. I have never used GDB to debug python before so I can't really help with it.

I am not debugging python — I am debugging a c++ shared object that is loaded by python into its process. this is the normal way it’s done with gdb, same as debugging any other shared object loaded by an executable.

**Comment by cjolivier01** [comment]
seems this was a bug in gdb asserting failure
