### ISSUE TITLE
Unable to expand variables

### ISSUE THREAD

**Issue by skebanga** [WebFreak001/code-debug#229]
I am getting an error "Could not expand variable" when attempting to expand `this`

I am using gdb 9.1, and running the app under gdb on the command line if I execute `p *this` I get the entire object's contents printed.

Similarly, trying to expand a local const reference (`const auto& foo = getFoo()`) I get the following error message:

> Could not expand variable: No symbol "function" in current context. (from data-evaluate-expression "*&function substr() { [native code] }")

I have tried under lldb 11 and having the same problem

**Comment by WebFreak001** [comment]
try setting `"valuesFormatting"` in your launch config to "disabled", "parseText" or "prettyPrinters"

Otherwise my extension doesn't do any more parsing and you are out of luck.

**Comment by skebanga** [comment]
Thanks! I'll test it out and report back

**Comment by skebanga** [comment]
"prettyPrinters" did it - thanks for the help!
