### ISSUE TITLE
Document install & update

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#23]
The procedure for installing or updating code-debug is unclear. Starting with this page:

https://marketplace.visualstudio.com/items?itemName=webfreak.debug

There is a green "Get Started" button at the top of the page which takes you to some good instructions (https://code.visualstudio.com/docs/editor/extension-gallery?pub=webfreak&ext=debug) on how to install code-debug. The first time I installed code-debug, I clicked on that button and installed without too much trouble. However, later I wanted to try to reinstall, and I clicked on the "Get Started" link on the right side of the webfreak.debug page under "Resources." That took me to https://github.com/WebFreak001/code-debug , and I wasn't sure how to proceed. I clicked "Download ZIP" but then couldn't figure out what to do with the zip file.

I would suggest several things to avoid confusion:

- On the webfreak.debug page, in the main text body section, insert a new, first section before the "Debug" section titled "Installation" with the text "To install this extension to Visual Studio Code, please follow the instructions at https://code.visualstudio.com/docs/editor/extension-gallery?pub=webfreak&ext=debug ."
- Rename the "Get Started" link under "Resources" to "Github page".
- Include a "HowToInstall" file in the zip file that contains instructions on how to install or update from the zip file (or if that's not practical, refer to the ext=debug page).
- Do something on the github code-debug page to discourage downloading the zip file and encourage following the proper installation instructions.

**Comment by WebFreak001** [comment]
um the link names (Get Started, etc) are generated by vscode so I can't change them. I could add a quick description to install GDB but installing any extension in vscode is the same with `ext install <name>`, so I probably won't add that

**Comment by JanKok** [comment]
Well, the Resources / Get Started link is certainly confusing. Are you saying I should complain to Microsoft/vscode?

Anyway, I don't think it would hurt to follow the other suggestions. For example, adding the "Installation" heading and text would give the user a 2/3 chance (instead of a 1/2 chance) of finding the right installation instructions. :-)

**Comment by WebFreak001** [comment]
Hm sure, gonna just add that to the README. I dont know if you can even modify the sidebar so the README is also fine

**Comment by JanKok** [comment]
I suggest you stick with my original suggestion, and make the Installation instructions: "To install this extension to Visual Studio Code, please follow the instructions at https://code.visualstudio.com/docs/editor/extension-gallery?pub=webfreak&ext=debug ." The instructions at that link worked for me the first time.

On the other hand, the installation instructions you just added to the README were confusing and led me astray. I tried ctrl-shift-P, filled in the line so it said "ext install debug" and hit ENTER. Code did some stuff, and then reported: "Info Cordova Tools 1.0.1 was successfully installed. Restart to enable it. Restart Now." I don't think I wanted Cordova Tools!

Please, don't assume your users will be very familiar with VSCode, Node.js, or the Microsoft or Linux way of doing things. I think most of your users will NOT be very familiar with some of those things. So please make your instructions VERY clear and step-by-step.

**Comment by JanKok** [comment]
Also, on the page https://github.com/WebFreak001/code-debug , I would suggest adding after "Native debugging for VSCode" near the top of the page, "Please read the README (link) section below for installation and usage instructions."

The problem is that the README is below the list of files, and may not be visible if you're looking at the top of the page. A visitor might just grab the zip file (as I did) and try to figure out how to install it.

**Comment by JanKok** [comment]
@WebFreak001 not sure if you saw the above two comments since you already closed this issue.

**Comment by WebFreak001** [comment]
The new Readme is now on the vscode page, so I don't need to link it everywhere because it's the first thing on the page. I'm gonna add some more information and maybe a Screenshot that shows it when I'm at home
