### ISSUE TITLE
Breakpionts lost.

### ISSUE THREAD

**Issue by kvinwang** [WebFreak001/code-debug#230]
I am using [rr](https://rr-project.org/) as a gdb backend.

$ rr --version
rr version 5.3.0

Config:
```json
      {
        "type": "gdb",
        "request": "attach",
        "name": "Attach to gdbserver",
        "executable": "${workspaceFolder}/x264",
        "target": ":50505",
        "remote": true,
        "cwd": "${workspaceRoot}",
        "valuesFormatting": "parseText"
      },
```

Steps to reproduce:
Step 1: `rr replay x264-2 -s 50505 -k`
Step 3: Attach to rr and add some breakpionts. It works fine.
Step 4: Disabling any breakpoint causes all breakpoints lost.

![code-debug-rr](https://user-images.githubusercontent.com/6442159/87108625-51696a00-c295-11ea-9ddd-cd893ac6b820.gif)

**Comment by WebFreak001** [comment]
Does `rr` offer a MI backend?

I use the break-delete MI command to remove a breakpoint, see https://github.com/WebFreak001/code-debug/blob/f2923480e45874324ca94badbe35c7ed80a5e172/src/backend/mi2/mi2.ts#L576

However in older GDB versions break-delete didn't take an argument and instead just cleared all breakpoints, which might be happening here. Can you check what happens if you manually run `-break-delete <num>` first on some breakpoint from the `i b` list to see if it properly deletes? If you enter an invalid number it might be possible that it could clear all breakpoints, you should check for this behavior.

Try enabling debug output (`"showDevDebugOutput": true, "printCalls": true`) and check if it actually runs break-delete on the correct breakpoint IDs.

**Comment by kvinwang** [comment]
`-break-delete <num>` can properly delete it.

```
-break-delete 2
{"token":28,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[]}}
i b
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   <MULTIPLE>         
1.1                         y     0x000055bad7a20d6a in x264_8_macroblock_analyse at encoder/analyse.c:3038
1.2                         y     0x000055bad7b4e186 in x264_10_macroblock_analyse at encoder/analyse.c:3038
3       breakpoint     keep y   <MULTIPLE>         
3.1                         y     0x000055bad79318c5 in x264_8_encoder_encode at encoder/encoder.c:3763
3.2                         y     0x000055bad79536c7 in x264_10_encoder_encode at encoder/encoder.c:3763
4       breakpoint     keep y   <MULTIPLE>         
4.1                         y     0x000055bad7936e61 in x264_8_lookahead_get_frames at encoder/lookahead.c:234
4.2                         y     0x000055bad7958c4c in x264_10_lookahead_get_frames at encoder/lookahead.c:234
5       breakpoint     keep y   <MULTIPLE>         
5.1                         y     0x000055bad7a4ff45 in clip_qscale at encoder/ratecontrol.c:2234
5.2                         y     0x000055bad7b7d58b in clip_qscale at encoder/ratecontrol.c:2234
6       breakpoint     keep y   <MULTIPLE>         
	stop only if h->sh.i_type == 2 (target evals)
6.1                         y     0x000055bad7a506ca in clip_qscale at encoder/ratecontrol.c:2317
6.2                         y     0x000055bad7b7dd10 in clip_qscale at encoder/ratecontrol.c:2317
7       breakpoint     keep y   0x000055bad78fc591 in main at x264.c:378
	breakpoint already hit 1 time

```

> Try enabling debug output (`"showDevDebugOutput": true, "printCalls": true`) and check if it actually runs break-delete on the correct breakpoint IDs.

Could you explain how i can enable this?

**Comment by WebFreak001** [comment]
ah I see it sends break-delete without any ID, probably because the breakpoint is undefined at that code.

It's a severe bug that there is no validation for undefined but it's also important to find out why it's undefined in the first place for you.

**Comment by kvinwang** [comment]
Actually, the `clearBreakPoints` is called instead of `removeBreakPoint`.
