### ISSUE TITLE
variable-view allows adjusting of type, leading to missing variable

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#232]
Note: This _isn't_ `gdb --version` >= 7.7.1; but I think it is a general issue in any case.

To reproduce:
* start debugging (I've used the most simple "start program" option)
* look at the variable view, see a type
* edit the type (ideally this wouldn't be possible) for example to nothing
* receive an error, for example "Could not continue: A syntax error in expression, near `'. (from gdb-set var myvar=)"
* depending on the actual error myvar may not be visible in the variable-pane any more

General question: Should it be possible to change the type? If not I suggest to place it as a tooltip, instead of "as value" as it is now. If it should be possible then it would be good to add some exception-handling and automated reset to the previous type if any issue occurs.

**Comment by WebFreak001** [comment]
Edit the type? I'm not sure what you mean or where you see that. Can you send a screenshot what you mean?

**Comment by GitMensch** [comment]
This is what I thought was the type

![grafik](https://user-images.githubusercontent.com/6699539/87526850-9faeac80-c68b-11ea-8d46-730916687e46.png)
![grafik](https://user-images.githubusercontent.com/6699539/87526943-bb19b780-c68b-11ea-8637-96accb08c2f3.png)
![grafik](https://user-images.githubusercontent.com/6699539/87526981-c79e1000-c68b-11ea-987c-2c55926c5765.png)
![grafik](https://user-images.githubusercontent.com/6699539/87527008-cec51e00-c68b-11ea-9a5f-80fa0b1d56c7.png)

but "unknown" is actual a value, no type, so... closing it, you may tag it as invalid.

**Comment by WebFreak001** [comment]
try setting it to `"banana"` actually

**Comment by GitMensch** [comment]
That would break the complete program as b_10 points to a place in a `char[]` - it needs a strcpy, or actually a memcpy - can this be achieved in the variable-view or only via debug console?

**Comment by WebFreak001** [comment]
setting it to a string should change b_10 so it no longer points to some place in a `char[]` but instead to the newly created string by gdb. If that breaks your program then don't change it in the variable view.
