### ISSUE TITLE
outdated package.json enableBreakpointsFor ?

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#233]
I've seen that in the (old) [debugger extensions documentation](https://vscode.readthedocs.io/en/stable/extensions/example-debuggers/)  this attribute is used, but when opening the project I see a warning

> Property enableBreakpointsFor is not allowed.

Checking the [API reference](https://code.visualstudio.com/api/references/contribution-points#contributes.breakpoints) shows that it should be defined above the debugger entries - but then the difference for mago seems to be not possible. Does the "mago only for d" setup actually work?

I've also recognized that the vscode dependency is quite old: 1.28+; with all the changes done since then maybe it is reasonable to update it again? [also with a warning: the empty `extensions`]

**Comment by soiamsoNG** [comment]
VSCode 1.54.3 not work, I think enableBreakpointsFor already dump.

**Comment by WebFreak001** [comment]
has been fixed in #280
