### ISSUE TITLE
debug with different debug and build machines

### ISSUE THREAD

**Issue by deviator** [WebFreak001/code-debug#235]
Hi! I try use remote debug with this config:
```json
{
    "version": "0.2.0",
    "inputs":[
        {
            "description": "address of device",
            "id": "addr",
            "type": "promptString",
            "default": "192.168.0.88"
        },
        {
            "description": "port of gdbserver",
            "id": "port",
            "type": "promptString",
            "default": "2000"
        }
    ],
    "configurations":[
        {
            "name": "on device",
            "type": "gdb",
            "request": "attach",
            "executable": "./subproj/bin/app",
            "target": "${input:addr}:${input:port}",
            "remote": true,
            "cwd": "${workspaceFolder}",
            "autorun": [
                "handle SIGUSR1 SIGUSR2 nostop"
            ],
            "valuesFormatting": "prettyPrinters"
        },
    ]
}
```
Application builds in docker container, and path of source files in this container and host machine (where I try debug) are different.
Then I try to set breakpoint in VSCode it pass to gdb with full path (at host machine) of source file and I get error:
```
No source file named /home/deviator/path/to/project/subproj/source/app.d.
```
gdb command `info sources` shows full path in container:
```
/workdir/subproj/source/app.d
```
In gdb console I can set breakpoint by use end part of full path:
```
(gdb) b subproj/source/app.d:20
Breakpoint 1 at 0xb48bc: file app.d, line 20.
```
How to tell extension to use local (`cwd`) path for breakpoint file names?
May be some mappings like [this](https://code.visualstudio.com/docs/cpp/launch-json-reference#_sourcefilemap) are available?

**Comment by deviator** [comment]
Found a workaround:
```json
            "autorun": [
                "handle SIGUSR1 SIGUSR2 nostop",
                "set substitute-path /workdir ${workspaceFolder}",
            ],
```

**Comment by GitMensch** [comment]
for remote connections and debug machine <-> local machine (IDE view) you may use `remote:sourceFileMap` now, for build machine <-> execution machine (GDB view) use `pathSubstitutions`.
