### ISSUE TITLE
Errors when trying to re-install

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#24]
This might be considered a user error, because what I did was install code-debug a second time, rather that uninstalling and reinstalling, or updating. I didn't read far enough in the installation instructions. :-)

However, I would suggest that code-debug (or perhaps VS Code itself) should check if the user is trying to reinstall, and give some more user-friendly error handling.

Attached is the output I got on my xterm, when I started Code, then tried to reinstall code-debug. Note that the first few lines, down to and including "bash: no job control in this shell" happen _every_ time I start Code. That's probably a separate issue, but if someone knows how to fix that, please let me know.

[InstallErrors.txt](https://github.com/WebFreak001/code-debug/files/139837/InstallErrors.txt)

**Comment by WebFreak001** [comment]
Um seems like a vscode bug. Try manually deleting the folder `/home/jan/.vscode/extensions/webfreak.debug-0.3.1`

If that works then report it as issue to Microsoft/vscode. Extensions don't handle anything about installation and deinstallation except they add some binaries. IIRC they can't call any code there

**Comment by JanKok** [comment]
Not sure what you mean by "If that works..." If I delete .../webfreak.debug-0.3.1 then start Code, Code still shows Debug 0.3.5 as an installed extension. If I click README in the Debug entry (in the installed extension list), Code displays something in the web browser and also shows in the Code window: "Info / Would you like to install 'Debug'? / Install Now / Cancel" If I click Install Now, it appears to install and gives about the same error messages as I reported before.

Do you want me to report this to Microsoft/vscode?

P.S. Thanks for developing this extension. I think it will be quite pleasant to use after it is polished up a bit more.

**Comment by WebFreak001** [comment]
yeah I think this is more an issue in vscode if its throwing that from the application and not from an extension. Don't forget to post clear steps to reproduce it there
