### ISSUE TITLE
Why does "connect" ignore "extraargs"?

### ISSUE THREAD

**Issue by wangnangg** [WebFreak001/code-debug#240]
Why does "connect" ignore "extraargs"? Is there a good reason for it?

see here: https://github.com/WebFreak001/code-debug/blob/f2923480e45874324ca94badbe35c7ed80a5e172/src/backend/mi2/mi2.ts#L248.

**Comment by WebFreak001** [comment]
I believe it was simply forgotten in the PR: https://github.com/WebFreak001/code-debug/commit/c831c4d4e4411d666dd068768627198f9ab6c6fd

I would be up for merging a PR inserting extraargs into preargs and removing the extraargs parameter again.

**Comment by GitMensch** [comment]
Fixed with #316, distributed with 0.26.0.
