### ISSUE TITLE
Failed to get Stack Trace: Selected thread is running. (from stack-list-frames --thread 2 0 20)

### ISSUE THREAD

**Issue by foreverhui** [WebFreak001/code-debug#247]
{
            "type": "gdb",
            "request": "attach",
            "name": "Attach to gdbserver",
            "executable": "./bin/executable",
            "target": "172.17.0.13:6666",
            "remote": true,
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        },
i have ```gdbserver   127.0.0.1:6666 --attach 23877```in the remote machine.but i can‘t use bt or get stack information.
```Cannot execute this command while the target is running.
Use the "interrupt" command to stop the target
and then try again.
Cannot execute this command while the target is running.
Use the "interrupt" command to stop the target
and then try again. (from interpreter-exec console "exec bt")
-exec bt
Undefined MI command: exec (from exec bt)
info locals
No frame selected.
No frame selected. (from interpreter-exec console "info locals")```

**Comment by GitMensch** [comment]
Checked as definitely working now. You'd have to set either a breakpoint in the ide or use the `stopAtEntry` launch configuration.
