### ISSUE TITLE
Please tag, both old versions and future ones

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#249]
It would be very useful if each of the releases would get an own tag as this helps a lot to follow the changes between them,

For older versions I volunteer to create a shell script using the technique from https://stackoverflow.com/a/21759466/5027456 using the [history of package.json](https://github.com/WebFreak001/code-debug/commits/master?before=4254bb15a616e99ba1a8e68aefa4d3babe0bb7b6+105&branch=master&path%5B%5D=package.json) to look up the commit hashes for each release (if I know that it is very likely to be applied).

For future ones: just tag directly before the release.

What do you think?

**Comment by GitMensch** [comment]
Coming back here as I've just wanted to check some differences between versions, which would be very easy to do if the versions would have a tag...

Ping @WebFreak001 Do you consider "tagging nicely"? As noted I'd be available to provide a script to tag old versions if I know that it is very likely to be applied.

**Comment by WebFreak001** [comment]
just tags would be good to have already. I wanted to see if now creating a new CI action would affect new tags/releases being created on old commits. Having an action generating a zipped extension to install would be nice before making the tags if that is the case.

**Comment by GitMensch** [comment]
> Having an action generating a zipped extension to install would be nice before making the tags if that is the case.

For CI/CD it is normally the other way around: you tag, possibly with a special schema like "vNN.NN" and then the action gets auto-triggered to publish via osvx for example and add a release from the tag which includes the vsix, too (tags on GitHub always lead to a "zipped" snapshot).

So, should I start to write the script for post-adding the old tags?

**Comment by GitMensch** [comment]
Now done (both the tag old/new and the inclusion of the .vsix as artifact).
