### ISSUE TITLE
"No symbol table is loaded.  Use the "file" command." with MSYS2 gdb 9.2

### ISSUE THREAD

**Issue by dan9er** [WebFreak001/code-debug#251]
OS: Windows 10 x64, Version 1909 Build 18363.1198  
VSCode version: VSCodium 1.51.1  
Extension version: 0.25.0 
Compiler: clang++ 11.0.0.0, C++11  
Build target: x86_64-pc-windows-msvc

To test my VSC configuration I wrote and compiled a test program in Debug mode via the CMake Tools extension. I've set up my launch.json and set a breakpoint. However when I click the Start Debugging button, GDB fails to attach and my program runs without stopping.

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "GDB",
            "type": "gdb",
            "gdbpath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
            "request": "launch",
            "target": "./helloVSCodium.exe",
            "cwd": "${workspaceRoot}/bin",
            "valuesFormatting": "parseText"
        }
    ]
}
```

Debug log:
```
No symbol table is loaded.  Use the "file" command.
Running executable
[New Thread 2872.0x137c]
[New Thread 2872.0x400c]
[New Thread 2872.0xfb4]
Hello C++ World from VS Codium and clangd! 
[Thread 2872.0x137c exited with code 0]
[Thread 2872.0xfb4 exited with code 0]
[Thread 2872.0x400c exited with code 0]
[Inferior 1 (process 2872) exited normally]
```

**Comment by GitMensch** [comment]
If you use the clang part to compile you also should debug using lldb, not with gdb (or ensure that you tweak the clang compilation to include the correct debugging format).

**Comment by GitMensch** [comment]
... possibly close this one?

**Comment by GitMensch** [comment]
Ping @dan9er - I guess it works fine when you use the "matching" debugger lldb (primarily a setting for the this extension)? Note: If I got that correctly you build in MSVC format (debug info in pdb) - that's no format GDB can read (LLDB can), so either change the compile target and keep the GDB setting or change the debugger in the launch config. I highly suggest to close this issue.
