### ISSUE TITLE
C++ Debugger enables control buttons, but application has not stopped

### ISSUE THREAD

**Issue by marklakata** [WebFreak001/code-debug#255]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I'm using gdbserver to run application.  Right after it starts, the CALL STACK shows a call position (sometimes) that is not inside my application, but looks like it is in the runtime start-up code.  Also, a warning appears in the lower-right corner "Failed to get Stack Trace: Selected thread is running. (from stack-list-frames --thread 1 0 20)".  The bug is that the debugger controls (Continue, Step Over, etc) that appears on the floating tool bar become enabled and you can click on them. However, clicking on them just generates another warning.  It makes it difficult to see if the program is running or halted, because us

Extension version: 0.25.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 3.10.0-514.26.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.87GB free)|
|Process Argv|--crash-reporter-id e51ea344-7c51-4694-bc47-6438a009dc4d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pa-dev01.lab.nanofluidics.com|
|OS|Linux x64 3.10.0-514.26.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (48 x 1246)|
|Memory (System)|251.50GB (106.40GB free)|
|VM|0%|
</details>

**Comment by GitMensch** [comment]
I _think_ that is nothing this extension can handle as vscode brings up the control buttons as soon as the program has started the debugging and gdb actually did something (in your case: trying to attach).

**Comment by GitMensch** [comment]
That should be solved now (just rechecked with a g++ project on gitpod, see #260) -> closed.

Note: you either would need to set a breakpoint in the ide or use the `stopAtEntry` launch attribute (and of course the program would have to be compiled with `-g`).
