### ISSUE TITLE
(win64, nasm/gcc) Unable to debug asm, "No source file named main.asm."

### ISSUE THREAD

**Issue by godstanis** [WebFreak001/code-debug#266]
- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1: **8.1**
  - [ ] it works on the command line with `gdb`: **vscode breakpoints are ignored, but manual gdb debugging is working as expected**
  - [x] `cwd` and `target` are properly set

Hey, I'm pretty new to assembly, and all the technical details of debugging it (specifically with visual studio code). I can't make the setup work with VSCode breakpoints.

My `launch.json` file:
(`workspaceRoot` = `"E:\Development\ASM\training"`)
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "${workspaceRoot}\\main.exe",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
    ]
}
```

My `main.asm` helloworld source:
```asm
segment .data
    msg db "Hello world!", 0xd, 0xa, 0

segment .text
global main
extern ExitProcess
extern printf

main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32

    mov     rcx, msg
    call    printf

    xor     rax, rax
    call    ExitProcess
```
My build process is simple:
```make
build:
	- nasm -g -f win64 main.asm
	- gcc main.obj -o main.exe
```
Now I have 3 files: `main.asm`, `main.obj` and `main.exe`

When I try to debug the application I set some breakpoints (`Allow Breakpoints Everywhere`) and then I see this in VSCode Debug Console:
`No source file named e:\Development\ASM\training\main.asm.` - only appears when I put some breakpoints via VSCode in my asm file.
```c
No source file named e:\Development\ASM\training\main.asm.
Running executable
[New Thread 4136.0x3e7c]
[New Thread 4136.0x349c]
Hello world!

[Thread 4136.0x349c exited with code 4294967295]
[Inferior 1 (process 4136) exited with code 037777777777]
Program exited with code 037777777777
```

**Comment by GitMensch** [comment]
Just to recheck: when you start debugging without any breakpoint sets the program stops on start, doesn't it? If not: add `"autorun": ["break main"]` to your launch.json.
If you then set a breakpoint via VSCode you see the issue again, correct? If you then remove it and add it by hand entering it in the console `b main.asm:11` and then `continue` - does it stop there?

BTW: which extension do you use for syntax highlighting the assembly source?

**Comment by GitMensch** [comment]
closed for missing feedback and "very likely outdated", can be reopened at any time if that still is an issue
