### ISSUE TITLE
Can't add breakpoints + variables don't show

### ISSUE THREAD

**Issue by PinyaColada** [WebFreak001/code-debug#267]
If submitting a bug please make sure

- [X ] If you are using gdb
  - [ 10.1 `gdb --version` >= 7.7.1
  - [ X] it works on the command line with `gdb`
  - [ X] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Screenshots are helpful but not required
![image](https://user-images.githubusercontent.com/72302480/116791638-f28f0e80-aabb-11eb-8be7-2620af10dfad.png)
Variables don't appear, and also I can't add breakpoints anywhere.

**Comment by WebFreak001** [comment]
did you compile your program with debug symbols? (according to your languages documentation)

what platform are you on?

**Comment by GitMensch** [comment]
Closing because of missing feedback and "works in general".
@PinyaColada: Can you please check if this works for you and if not "does it work with plain gdb"? If the later is the case, but it doesn't work here we should reopen - but really need more information for that.
