### ISSUE TITLE
adding breakpoints from vscode panel seldom works (gdb connect to remote debugserver by ip)

### ISSUE THREAD

**Issue by zxtxin** [WebFreak001/code-debug#268]
my configuration is below
            "name": "test",
            "type": "gdb",
            "request": "attach",
            "target": "172.31.16.1:1025",
            "executable": "test.elf",
            "cwd": "${workspaceFolder}",
            "remote": true,
            "gdbpath": "riscv64-unknown-elf-gdb",
            "printCalls":true,
            "showDevDebugOutput":true,

When I start to debug my program, I can add the breakpoint in the Debug Console by "break" command. For example, if I enter "break main" in the Debug Console and then start to run, the breakpoint will work at the correct position and the source code will be oriented to the appropriate position.
![image](https://user-images.githubusercontent.com/5063358/117600954-92fdc680-b17f-11eb-9381-279186e085af.png)
But when i add breakpoints from Breakpoints Panel, It seldom works. Most times, the program runs as if no breakpoints were added. There are no relevant logs such as "break" "break-insert" in Debug Console.
![image](https://user-images.githubusercontent.com/5063358/117601905-f852b700-b181-11eb-8bf4-ff7485cac382.png)
There are only a few times that it works and I can find breakpoint relevant logs in Debug Console under these circumstances. I will attach a screenshot of this if I get one.
There are no differences between operations I did of the success and the failure. I don't no why it sometimes works.

**Comment by zxtxin** [comment]
![image](https://user-images.githubusercontent.com/5063358/117604381-d2c8ac00-b187-11eb-8dad-2fd6e6bd70ba.png)

**Comment by zxtxin** [comment]
I'm working on WSL

**Comment by WebFreak001** [comment]
checked #167 ?

**Comment by Dynell** [comment]
Hi, i have the same problem.
Also working on WSL2 and connecting to a remote gdbserver running on an ARM target.
Adding breakpoints only works when setting them before launch.
When I add a breakpoint while program is running the breakpoint gets ignored.
But when I hit CTRL+C into the gdbserver terminal the program is paused and now I can add a breakpoint.
Is there a problem sending CTRL+C to the gdbserver on windows?

**Comment by Dynell** [comment]
> 
> 
> Hi, i have the same problem.
> Also working on WSL2 and connecting to a remote gdbserver running on an ARM target.
> Adding breakpoints only works when setting them before launch.
> When I add a breakpoint while program is running the breakpoint gets ignored.
> But when I hit CTRL+C into the gdbserver terminal the program is paused and now I can add a breakpoint.
> Is there a problem sending CTRL+C to the gdbserver on windows?

It worked for me when I add "autorun": ["break main"] to the launch config.
After this the program stops at main and I can continue (without this line I can't pause the program).
Then I can hit the "Pause" button and add a breakpoint, while the program is paused.
Adding a breakpoint while program is running does not work for me.

**Comment by GitMensch** [comment]
Should be fixed with #313 (and the setting of the "main" breakpoint will also be able through the new settings `stopAtConnect ` and `stopAtEntry` with the 0.26 release.
