### ISSUE TITLE
Not repeating last gdb command when pressing enter

### ISSUE THREAD

**Issue by Ta180m** [WebFreak001/code-debug#270]
Expected behavior: Pressing enter in the debug console runs the last gdb command, like what happens in normal gdb.

Actual behavior: A blank line is printed and nothing happens.

**Comment by GitMensch** [comment]
Pressing enter was one of the first things I've did, too.

After I gave this some thought (the history is possibly available via dap, if not then the last command could likely be stored in the gdb backend and be executed when an enter is received, and if not could be resolved by `show commands`) I vote to close this issue.

Reasoning: this is explicit a vscode extension, which does not follow GDB's UI decisions.
The most likely commands to re-execute are the ones for navigating (there's the debug toolbar and keyboard shortcuts for those) and some related to frame list (shown as extra window).

I therefore "vote" for closing this.

**Comment by Ta180m** [comment]
OK, I will close this issue. (Also I don't use this extension anymore)
