### ISSUE TITLE
I am trying to debugging my custom qemu with code-debug, it's can debugging with vscode-cpptools, but not code-debug. 

### ISSUE THREAD

**Issue by lygstate** [WebFreak001/code-debug#273]
If submitting a bug please make sure

- [ *] If you are using gdb
  - [ * ] `gdb --version` >= 10.2
  - [ * ] it works on the command line with `gdb`
  - [ * ] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by WebFreak001** [comment]
what doesn't work?

**Comment by GitMensch** [comment]
Closed because of missing basic information what the issue actually is - feel free to comment with more info and we can re-open this issue.
