### ISSUE TITLE
Missing quotation for variables with spaces leads to "Could not expand variable: Variable object not found"

### ISSUE THREAD

**Issue by martin-fleck-at** [WebFreak001/code-debug#278]
In my program I have a vector variable of a certain type, e.g., `cl::Platform`. When I list all children using GDB with the M2 interface, the name of that variable is reported as `var_1_platforms::_Vector_base<cl::Platform, std::allocator<cl::Platform> >` (note the spaces in the name). But when I try to get the children of that variable (`var-list-children --all-values <name>`) I receive a `Could not expand variable: Variable object not found` exception. I traced the issue to the spaces in the variable name as they break the parsing of the name. This can be easily reproduced on the command line.

Quoting the variable name fixes the issue for me and I noticed that there are already quotation marks around some other commands in the MI2 class, e.g., around expression when we create a variable. I will push a PR adding those quotation marks shortly.

**Comment by GitMensch** [comment]
218d824 should have fixed this, so I assume it can be closed. If there is still an issue please report and we'll reopen.
