### ISSUE TITLE
Launch in a separate terminal window

### ISSUE THREAD

**Issue by WebFreak001** [WebFreak001/code-debug#28]
See https://github.com/WebFreak001/code-debug/issues/26

**Comment by JanKok** [comment]
Thanks for providing this feature. I have a couple of problems with it.
1. The first line of the new terminal window displays: `&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"`. The terminal window basically works, though. My program can read and write to it.
2. Each time I start my program in Code, I get a new terminal window. The old one isn't closed or reused. Maybe there should be some options to control what happens to the previous terminal.

**Comment by WebFreak001** [comment]
1. thats something to do with your OS. For example on linux mint i had that issue too but on arch I don't have it anymore. Need to look into those permission things.
2. I didn't find a way to close it automatically because GDB doesn't send any signal to it. I can maybe manually hold a reference to the console and close it then

**Comment by LaurentTreguier** [comment]
I don't know if reviving an old issue is a good idea, but I'm having the exact same problems as @JanKok and I've noticed that Microsoft's [cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension manages to somehow work them out. It finds out the default terminal, doesn't display this first line and closes it when the program ends... I have no idea how they are doing it though.

**Comment by WebFreak001** [comment]
Hm I can probably also make it close when gdb stops because I can just hold a reference to the PID of the terminal. But I would have no idea how to fix that first line

**Comment by LaurentTreguier** [comment]
I just tried looking into cpptools' code to see if I could get something out of it, but it looks like they use a bunch of precompiled dll's and binaries bundled with the extension...
