### ISSUE TITLE
can't add a breakpoint for C++

### ISSUE THREAD

**Issue by playgithub** [WebFreak001/code-debug#286]
## Env
OS: Linux (x64)
gdb: 10.2
vscodium: 1.59.1

## Required Info
- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1
  - [x] it works on the command line with `gdb`
  - [x] `cwd` and `target` are properly set

## Description
A single file hello-world project.

`HelloApp.cpp`
```cpp
#include <iostream>

int main(int argc, char **argv)
{
    int a = 1;
    int b = 2;
    int c = a + b;
    std::cout << c << std::endl;
    return 0;
}
```

`tasks.json`
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "g++ -g HelloApp.cpp",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

`launch.json`
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "./a.out",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
    ]
}
```
## Problem
can't add a breakpoint by the methods below
* F9
* vscode command: `Debug: Toggle Break`
* click in editor at the position of indicator for breakpoint

**Comment by WebFreak001** [comment]
it might work if you install the C/C++ extension from the marketplace, but this should be fixed with next release

**Comment by playgithub** [comment]
> it might work if you install the C/C++ extension from the marketplace
I've installed it from the default extension marketplace for vscodium, i.e. open-vsx
Do you mean the extension marketplace by microsoft?

**Comment by GitMensch** [comment]
There are multiple C/C++ extensions in the marketplace, as a workaround you _could_ try the following

> Use the Command Palette (Ctrl+Shift+P) to search for Settings, or navigate to File > Preferences > Settings from the menu.  Select the User tab, and then User > Features > Debug.  Activate the Allow Breakpoints Anywhere option.

**Comment by playgithub** [comment]
Thanks
