### ISSUE TITLE
Failed to start MI Debugger: pid or remoteDebugger is mandatory

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#290]
launch.json has:

```jsonc
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "attach",
            "name": "attach me",
            "target": ":12345",
            "remote": true,
            "gdbpath": "d:\\msys64\\mingw64\\bin\\gdb-multiarch.exe",
        },
    ]
}
```

BTW: is it correct to set the `"target": "extended-remote :12345"` as seen in a different issue if I want to use extended-remote?

**Comment by WebFreak001** [comment]
yes target: extended-remote can be used

You can see the special case here: https://github.com/WebFreak001/code-debug/blob/5151db04ee78063637cf273c1c1a75450a3cfc5e/src/backend/mi2/mi2.ts#L215

**Comment by maxgolov** [comment]
> BTW: is it correct to set the "target": "extended-remote :12345" as seen in a different issue if I want to use extended-remote?

What worked for me:
- `"remote": false`
- `pid` must be specified by autorun script.. Because you can't specify it for `target` that starts with `extended-remote`.

Would it make sense to possibly add separate config options for `launch.json` , such as:
- `"extended-remote": true`
- `"processId": 12345` or `"pid": 12345`

?

This is the config that worked for me for extended-remote use-case:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "attach",
            "executable": "GdbSample",
            "cwd": "${workspaceFolder}/../../Install/Debug/Target-aarch64-xxxxx-linux-gnu/bin/",
            "name": "(gdb) Attach to Target",
            "target": "extended-remote 192.168.1.50:2345",
            "remote": false,
            "gdbpath": "C:/msys64/mingw64/bin/gdb-multiarch.exe",
            "printCalls": true,
            "valuesFormatting": "parseText",
            "showDevDebugOutput": true,
            "autorun": [
                "attach 12345"
            ]
        }
    ]
}
```

**Comment by GitMensch** [comment]
Documentation was updated, inconsistencies handled with #330.
