### ISSUE TITLE
Empty debugger for Ada on VSCode.

### ISSUE THREAD

**Issue by geru-scotland** [WebFreak001/code-debug#291]
I am experiencing a weird issue with Native Debugger on VS Code (Mac OS Big Sur), I am following this [guide](https://github.com/AdaCore/ada_language_server/wiki/getting-started),  but can't make it work at all. I have installed the Native Debug extension, gdb is installed...etc. I have been working with Ada for some time but just thought about starting to debug my projects. I am first trying to make it work with a simple project hello_world, like explained on the guide.

I can start the debugger, but it won't show anything, not the variables or the call stack, nothing - just which breakpoints I did toggle. The controls that allow you to step through the code are also empty, as you can see here: https://i.stack.imgur.com/eJ7dC.png

The content of my launch.json is:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        

        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": ".objs/hello_world",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "preLaunchTask": "ada: Build current project",
        }
    ]
}
```

The rest are also the same than the guide's. Any help would be greatly appreciated! I am a bit lost and don't know what to do. Any ideas?

Thanks!

**Comment by GitMensch** [comment]
The next steps on the command line variant would be:
* `break hello_world.adb:9` ENTER
* `break hello_world.adb:12` ENTER
* `run` ENTER
* the program should run and stop in one of those lines,  `list` should show the context

If that works: are you sure that you use the same `gdb` from within vscode? I _guess_ you may need to adjust the `gdbpath` setting in your launch.json to point to the same `gdb` binary you've used from the command line.
