### ISSUE TITLE
Path Substitution Not Properly Escaped

### ISSUE THREAD

**Issue by brownts** [WebFreak001/code-debug#294]
Windows/DOS paths in the pathSubstitutions configuration attribute are not escaped before being sent to the debugger.  Thus on Windows, a typical path cannot be used as-is, but instead must be escaped again within the launch.json:

```json
"pathSubstitutions": { "C:\\\\test1": "C:\\\\test2" }
```

Not only is it a nuisance to have to do this (or switch to POSIX style paths), but it is also problematic when attempting to use predefined variables (e.g., ${workspaceFolder}) in the substitution paths.  The predefined VSCode variables use the path format of the host OS, so become unusable in this context.

**Comment by GitMensch** [comment]
It sounds like you could open a PR to fix that, what do you think?

**Comment by GitMensch** [comment]
Fixed with #295 thanks to @brownts.
