### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by csholmq** [WebFreak001/code-debug#3]
Not on the clear on what I should change "target" to. I assume the final executable?

I'm actually looking for remote GDB debugging. Perhaps this is the wrong plugin for me?

**Comment by WebFreak001** [comment]
Oh yeah `target` is the compiled executable. I didn't look into remote debugging yet but I will add it in the future. I'm gonna update the instructions

**Comment by csholmq** [comment]
Excellent! I would assume it would have a similar approach to `"type": "node"`and `""request": "attach"` for Node debugging.
