### ISSUE TITLE
[Help] How to run -iex command in GDB?

### ISSUE THREAD

**Issue by selvavm** [WebFreak001/code-debug#309]
I am trying to use GDB with Rust. I found that I will have to add pretty printer by invoking a python script. I am able to see the variables pretty printed in CMD if I call below directly,
`gdb -iex "source selva.py" .\target\debug\test.exe`

When I do the same with `launch.json`, I get below error,
````
undefinedgdb: unrecognized option `--iex "source selva.py"'
Use `C:\msys64\mingw64\bin\gdb.exe --help' for a complete list of options.

```

Below is my configuration,
```
        {
            "type": "gdb",
            "request": "launch",
            "name": "(gdb) Debug Launch",
            "target": "${workspaceRoot}/target/debug/${workspaceRootFolderName}.exe",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "prettyPrinters",
            "gdbpath": "gdb",
            "arguments": "fsettings.toml",
            "debugger_args": ["-iex \"source selva.py\""]
        }
```

**Comment by selvavm** [comment]
Nevermind. Fixed with using `autorun` instead of `iex`

**Comment by GitMensch** [comment]
Just out of interest: Can you please check if `debugger_args": ["-iex", "source selva.py"]` work, too?
The difference is that `autorun` executes _after_ the program is loaded (like `-ex` commands), `-iex` executes that before.
