### ISSUE TITLE
"go to cursor location" does not work with ssh connection

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#332]
The reason is that this call is handled from mi2.ts, while the source conversion is done in mibase.ts.

I have a working version that passes the MI2 instance to MI2DebugSession and then access it to let it do the conversion.
Another alternative would be the other way around - moving the path conversion ssh<->local to be stored and done from the MI2DebugSession.

@WebFreak001 @brownts Are both or one of those "dirty"?
I'm available for doing a PR (I actually have the code for the variants above ;-), just would like to know which way (if one) I shpould take before creating a PR.

**Comment by GitMensch** [comment]
Nope, when I've tried the "go to" feature led to `break-insert -t` (MI2.goto); but the "run to cursor", which I _think_ should use this, just creates a "normal" breakpoint now (see debug output, there's even no need to use the debugger to debug the extension as I did; which showed the call event to be a plain "breakpoint add").

The questions here:

* Why does we get an event of "breakpoint add" instead of goto (or is this just a local issue)?
* Is the change itself "correct" or should it be done different?
* Not sure: Why are some commands handled in MI2 while others are in MI2DebugSession?

**Comment by GitMensch** [comment]
See, we were both confused by this function :-)
But yes, both" run until" and "go to (jump)" are useful; for the later always look out for possible stack trashes or resource leak - best to only jump within the same method and force a return where in an upper method.

The most common use case for jump is going backwards without total `record full` / `record btrace` (or commonly more better: use of `rr`) to inspect a previous state again - or to jump backwards, fix the "code" by assigning variables as they should be, then continue.

I totally agree that the design should be better stated, especially as I'm coming back to the code after weeks without ever "been in completely" I wonder about the same design issues (which partially come from the vscode<->DAP part, partially from the "multiple debuggers" part and partially because "that's the way @WebFreak001 wants it", and partially because there was no better design found yet).
Having more class and method comments _and_ the general design "as good as known" in HACKING.md would help a lot. @brownts Would you mind adding your current view there so we can improve it step by step?

For the issue at hand: if the SSH awareness is in MI2DebugSession then the source file mapping should be done there completely (with the actual code for that in a separate file - as it is now).

**Comment by GitMensch** [comment]
... thinking about it more: the "run until" part is still created with a non-temporary breakpoint - that seems wrong. Either a temporary breakpoint and `exec-continue` should be used there or `-exec-until` (maybe let the user decide, some people are confused when they land somewhere else (because the scope was left), others are confused when the inferior runs and exits because the place is never reached.

**Comment by GitMensch** [comment]
OK, so we can't do anything about that for now, leaving the original issue that we need the sourceFileMap handling somewhere and possibly a move of some functions between MI2DebugSession <-> MI2.

**Comment by brownts** [comment]
I don't believe any functions need to be moved.  I suggested a 1-2 line change in my PR comment which just adds the mapping in the MI2DebugSession class.  That would be consistent with where the other breakpoint and stack frame mapping is performed.

**Comment by GitMensch** [comment]
Ah, now I see. In this case... retested again with master -> got "no source file x. found" (the request was `-break-insert - t x:\\some\\file.c`), then applied your suggested change - works like a charm and is _much_ clearer.
Thank you!
