### ISSUE TITLE
Not managing to debug D code in Windows

### ISSUE THREAD

**Issue by p0nce** [WebFreak001/code-debug#336]
There is no particular instructions for Windows, having debugging in native-debug
Nothing I've tried work.
I don't know what debuggers to install, or what to point to.

**Comment by GitMensch** [comment]
In general this extension "debugs" with a "native debugger" (thus also its name).
You can choose a bunch of native debuggers (foremost GDB [or frontends that support GDB/MI well enough], but also LMDB and Mago).

From https://wiki.dlang.org/Debuggers it looks like it all depends on the format of your debugging which is different per compiler/platform.

So the very first question: Do you have one of these setup and can debug your D code as you expect and now look for an IDE experience? If the answer is "yes", then we can go on with the setup (starting with: What debugger do you use and know that works, what did you tried as a launch configuration, ...), if the answer is one of "those debuggers don't have support for debugging D", "I don't have those debuggers working" then we can go on.

**Comment by WebFreak001** [comment]
if you have code-d installed try checking out the debugging section there: https://github.com/Pure-D/code-d/blob/master/docs/debugging.md

**Comment by p0nce** [comment]
> if you have code-d installed try checking out the debugging section there: https://github.com/Pure-D/code-d/blob/master/docs/debugging.md

This is good, and nothing I've read in https://github.com/Pure-D/code-d or https://marketplace.visualstudio.com/items?itemName=webfreak.code-d pointed me on the right resources. **This is a bug.**

I'm not looking for guidance for myself, but for the hundreds that will have the same issue.

**Comment by WebFreak001** [comment]
it' described in the welcome guide (standard feature of vscode where you can read about all kinds of features) which is also opened as first thing when you install code-d for the first time and the command is called `code-d: Open User Guide`, I don't think there is much more I can do to make users read it without annoying them.

For this extension for the instructions how to use it, see the README. For instructions how to debug with vscode see the official Microsoft guide: https://code.visualstudio.com/Docs/editor/debugging

Also as this debug extension isn't actually really related to the code-d extension, I will close this issue.
