### ISSUE TITLE
0.26.0 regression with remote debug: GDB cannot find source files because of lower-casing file paths

### ISSUE THREAD

**Issue by danocharron** [WebFreak001/code-debug#346]
I noticed on your latest version 0.26.0 that the breakpoint paths and file names are now all lower case.
My source file names and paths have upper-case and lower-case characters. 

I am remote debugging from Windows to Linux through ssh.

I was looking forward to your improvements, but for now I guess I will revert to your 0.25.1 version. 

More:

------------------
If I set  "stopAtEntry": true, in my launch.json 
Your APP will set a breakpoint at the Src/main.cpp 

GDB -> App: {"outOfBandRecord":[{"isStream":true,"type":"console","content":"Temporary breakpoint 2, main (argc=1, argv=0x7fffffffebc8) at Src/main.cpp:4231\n"}]}
Temporary breakpoint 2, main (argc=1, argv=0x7fffffffebc8) at Src/main.cpp:4231

------------------
If I then put a breakpoint in the editor your APP will set the breakpoint like this:

GDB -> App: {"token":19,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["bkpt",[["number","8"],["type","breakpoint"],["disp","keep"],["enabled","y"],["addr","<PENDING>"],["pending","/root/platform/src/main.cpp:4252"],["times","0"],["original-location","/root/platform/src/main.cpp:4252"]]]]}}

NOTE: the path name needs to have "Src" not "src"

**Comment by brownts** [comment]
Hi @danocharron, thanks for this report.

Can you share your launch configuration?  I suspect that this has to do with the path mapping configuration between the Windows and Linux machines, but I'd like to get a better understanding of what you currently have setup, so we can replicate the scenario.

**Comment by danocharron** [comment]
Here is my launch.json

I have noticed some from previous rev to this 0.26.0 -  I will send in
another email.

{
    "type": "gdb",
    "request": "launch",
    "name": "Launch Program (SSH)",
    "target": "/root/platform/egsgame",
    "cwd": "${workspaceRoot}",
    "stopAtEntry": true,
    "showDevDebugOutput": true,
    "internalConsoleOptions": "openOnSessionStart",
    "ssh": {
        "sudo": "true",
        "host": "10.20.12.101",
        "cwd": "/root/platform/",
        "user": "root",
        "password": "*****",
        "port": 22,
        "forwardX11": false,
        "useAgent": false,
        "bootstrap": "killall -9 onboard;killall -9 egsgame;export
DISPLAY=:0;cd /root/platform",
        "sourceFileMap": {
            "/root/platform/": "${workspaceRoot}/"
        }
    },
    "valuesFormatting": "parseText"
},

**Comment by danocharron** [comment]
This is setting a breakpoint at the same place running older and new
versions of extension.


Version 0.25.1  - THIS WORKS Note the upper-case letters capitalized

GDB -> App:
{"token":15,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[]}}

GDB -> App:
{"token":16,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["bkpt",[["number","2"],["type","breakpoint"],["disp","keep"],["enabled","y"],["addr","0x000000000076b21f"],["func","SetupManager::SetupManager()"],["file","Src/Sys/Admin/SetupManager.cpp"],["fullname","/root/platform/Src/Sys/Admin/SetupManager.cpp"],["line","274"],["thread-groups",["i1"]],["times","0"],["original-location","/root/platform/Src/Sys/Admin/SetupManager.cpp:274"]]]]}}

GDB -> App:
{"token":17,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["bkpt",[["number","3"],["type","breakpoint"],["disp","keep"],["enabled","y"],["addr","0x000000000076b24e"],["func","SetupManager::SetupManager()"],["file","
Src/Sys/Admin/SetupManager.cpp
"],["fullname","/root/platform/Src/Sys/Admin/SetupManager.cpp"],["line","276"],["thread-groups",["i1"]],["times","0"],["original-location","/
root/platform/Src/Sys/Admin/SetupManager.cpp:276"]]]]}}





Version 0.26.0 – THIS DOES NOT WORK

GDB -> App: {"outOfBandRecord":[{"isStream":true,"type":"log","content":"No
source file named /root/platform/src/sys/admin/setupmanager.cpp.\n"}]}

No source file named /root/platform/src/sys/admin/setupmanager.cpp.

GDB -> App:
{"token":16,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["bkpt",[["number","5"],["type","breakpoint"],["disp","keep"],["enabled","y"],["addr","<PENDING>"],["pending","/root/platform/src/sys/admin/setupmanager.cpp:274"],["times","0"],["original-location","/root/platform/src/sys/admin/setupmanager.cpp:274"]]]]}}

GDB -> App: {"outOfBandRecord":[{"isStream":true,"type":"log","content":"No
source file named /root/platform/src/sys/admin/setupmanager.cpp.\n"}]}

No source file named /root/platform/src/sys/admin/setupmanager.cpp.

GDB -> App:
{"token":17,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["bkpt",[["number","6"],["type","breakpoint"],["disp","keep"],["enabled","y"],["addr","<PENDING>"],["pending","/
root/platform/src/sys/admin/setupmanager.cpp
:276"],["times","0"],["original-location
","/root/platform/src/sys/admin/setupmanager.cpp:276"]]]]}}

**Comment by brownts** [comment]
Thanks for that additional information.  I'm pretty sure I know where the issue is.  I'll take a look at it within the next few days and should be able to generate a new release with this fixed.

**Comment by GitMensch** [comment]
@brownts When working on this can you please check the issue in #332? The main question is _where_ the translation should be done.
