### ISSUE TITLE
the internal structure of extension ignores a nesting level

### ISSUE THREAD

**Issue by ndk** [WebFreak001/code-debug#35]
for example:
```cpp
#include <iostream>
#include <string>

struct A
{
  std::string infoa;
};

struct B
{
  std::string infob;
  A* a;
};

struct C
{
  std::string infoc;
  B* b;
  
  void Test()
  {
    std::cout << infoc << ", " << b->infob << ", " << b->a->infoa << std::endl;
  }
};

int main()
{
  A* a = new A{"aaa"};
  B* b = new B{"bbb", a};
  C c = C{"ccc", b};
  c.Test();
  return 0;
}
```

![code-debug](https://cloud.githubusercontent.com/assets/591500/13373881/500d0374-dd84-11e5-9422-072f8bf2c901.png)

same commands passed directly to gdb

> 7-data-evaluate-expression "*this"
7^done,value="{infoc = \"ccc\", b = 0x614c50}"
(gdb) 
8-data-evaluate-expression "*b"
8^done,value="{infob = \"bbb\", a = 0x614c20}"
(gdb) 
9-data-evaluate-expression "*a"
9^error,msg="Attempt to take contents of a non-pointer value."
(gdb)

**Comment by WebFreak001** [comment]
this is a known issue, i need to change the variable parsing a bit for that and rewrite the way how variables are extended

**Comment by ndk** [comment]
how about fwrap all logic with try/catch?

**Comment by WebFreak001** [comment]
no thats not needed, instead i just implemented the reject methods. However it will not fix nested variables, just the infinitely loading circles

**Comment by WebFreak001** [comment]
hm I cant get it to work in GDB. If I do `p (*b).a` it tells me there is a syntax error

**Comment by WebFreak001** [comment]
but if that syntax would work, the implementation would work

**Comment by WebFreak001** [comment]
This is now pushed. I need to make the combine character customizable (currently its "." but in C/C++ its probably "->" instead of "." to get a member of a pointer)
