### ISSUE TITLE
how to dynamic load shared library in launch.json

### ISSUE THREAD

**Issue by binbinlau** [WebFreak001/code-debug#350]
If submitting a bug please make sure

- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1
  - [x] it works on the command line with `gdb`
  - [x] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by binbinlau** [comment]
i can't config command "set solib-search-path xxx" for load shared library

**Comment by brownts** [comment]
Hi @binbinlau, you should be able to configure this via the `debugger_args` option:
```yaml
debugger_args: ["-iex", "set solib-search-path xxx"]
```

**Comment by GitMensch** [comment]
Should we make an explicit note about this case in the user documentation (README.md) or should we close this directly?

**Comment by brownts** [comment]
I don't believe there is any further action on this.  Feel free to re-open this issue if you feel this was not sufficiently addressed.
