### ISSUE TITLE
support multithread debugging

### ISSUE THREAD

**Issue by WebFreak001** [WebFreak001/code-debug#36]

**Comment by WebFreak001** [comment]
Moved to when vscode actually supports multithreaded debugging

**Comment by outcoldman** [comment]
@WebFreak001 this is how Microsoft C++/C debugger implements it
<img width="290" alt="screen shot 2016-04-14 at 6 29 52 pm" src="https://cloud.githubusercontent.com/assets/597158/14548768/f05ef814-026e-11e6-8a11-97c1591a8643.png">

So I guess it is supported by VSCode, just in weird way.

**Comment by zcnet4** [comment]
MI2DebugSession constructor parameter threadID is passed by vscode?

class MI2DebugSession extends vscode_debugadapter_1.DebugSession {
    constructor(debuggerLinesStartAt1, isServer = false, threadID = 1) {
        super(debuggerLinesStartAt1, isServer);
        this.variableHandles = new vscode_debugadapter_1.Handles();
        this.threadID = 1;
        this.threadID = threadID;
    }

**Comment by zcnet4** [comment]
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts 

I look at debugSession.ts code and found that threadID is not vscode passed. When the debugging is interrupted, you can use the info thread command to get the number of threads
