### ISSUE TITLE
Stop using lldb-mi

### ISSUE THREAD

**Issue by rotu** [WebFreak001/code-debug#366]
It seems that, while `lldb-mi` was once part of the core LLVM release, [it is no longer](https://lists.llvm.org/pipermail/lldb-dev/2019-August/015357.html). Additionally, [it hasn't had a release on Ubuntu since LLVM 9](https://packages.ubuntu.com/search?suite=impish&arch=any&mode=exactfilename&searchon=contents&keywords=lldb-mi).

It would be nice to remove this dependency and use LLDB directly.

**Comment by brownts** [comment]
Hi @rotu, do newer versions of LLDB support an MI interface?  I was under the impression that `lldb-mi` was that interface and it was just being handled independently of LLDB, per the [release notes in 9.0.1](https://releases.llvm.org/9.0.1/docs/ReleaseNotes.html#changes-to-lldb):
> This release will be the last where lldb-mi is shipped as part of LLDB. The tool will still be available in a [downstream repository on GitHub](https://github.com/lldb-tools/lldb-mi).

**Comment by WebFreak001** [comment]
as `lldb-mi` can built against any LLDB version now I don't see any reason to remove the support for it.

There is no dependency on lldb-mi in code-debug, but we do support it if the user wants to use it, so I don't think we need to change anything.

**Comment by rotu** [comment]
@brownts I *think* the expectation is that tools use the [Scripting Bridge API](https://lldb.llvm.org/design/sbapi.html).

TBH I'm missing a lot of history here, so I don't understand why `lldb-mi` is required - just that it is not a dependency provided by `apt` (Ubuntu) nor `homebrew` (Mac OS).

@WebFreak001 Okay, if LLDB-MI is still a requirement, perhaps it bears mentioning how to get it. Additionally, these instructions are out-of-date for Mac:

> Note: for LLDB you need to have lldb-mi in your PATH
> 
> If you are on OS X you can add lldb-mi to your path using ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi /usr/local/bin/lldb-mi if you have Xcode.

**Comment by WebFreak001** [comment]
lldb-mi is not required, you can optionally use it if you have it.

Feel free to use GDB instead.

**Comment by brownts** [comment]
@rotu, this extension is based on interfacing with debuggers that support the GDB MI as documented [here](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html), and `lldb-mi` provides a GDB MI compatible interface, thus the need for this extension to require it if you want to debug via `lldb`.  I don't believe there is currently any expectation to support lldb-specific interfaces at this point in time.

If this is not sufficient for your needs, you could use GDB as @WebFreak001 mentioned, or you could try a different extension.  I'm not sure which editor you are using to debug with, but if it is VSCode, there is a dedicated `lldb-vscode` extension (see [here](https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-vscode)) that might better meet your needs, that is shipped with LLDB itself.  It looks like there are some setup instructions, but there might be a pre-packaged version in the marketplace.

**Comment by rotu** [comment]
> lldb-mi is not required, you can optionally use it if you have it.
> 
> Feel free to use GDB instead.

I mean “lldb-mi is a requirement in order to use lldb”. This extension comes up when you search for “lldb” and not when you search for “lldb-mi” - the additional dependency is unexpected.

**Comment by rotu** [comment]
@brownts thanks for the pointer! I didn’t realize VSCode shipped this, as it’s not listed in the extension Marketplace. But I expect one of the marketplace LLDB extensions is just a thin wrapper around it

**Comment by WebFreak001** [comment]
in the vscode marketplace you should find [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) which works very well and uses LLDB's native interfacing.
