### ISSUE TITLE
Does this extension support Remote SSH mode (the MS addon)?

### ISSUE THREAD

**Issue by Darker** [WebFreak001/code-debug#367]
VS Code supoorts remote development via SSH tunnel and that is what I am currently using. Here is the description of the feature: https://code.visualstudio.com/docs/remote/ssh

The way I understand it, extensions should generally be unaware of this and think they are running on the remote machine.

With that in mind, I set up the launch config as if it was a local GDB launch:

```
        {
            "type": "gdb",
            "request": "launch",
            "name": "Debug bootcamp",
            "target": "../build/myexecutable",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
```

However, I get no results. When I start the debugging, the Debug console will show "Running executable" in orange text and nothing else will really happen. On the top side of the screen, I can see the Pause/Step/Stop controls, but pause does not really do anything.

So is this compatible with the remote SSH feature, or do I have to use GDB server? Obviously using GDB directly would be nicer as it does not require additional config of hostname and port.

**Comment by KyrietS** [comment]
Are there any other ways to debug this extension on SSH mode?

- I have my vscode connected via SSH to remote machine. 
- I have **Native Debug** extension installed on remote. 
- My launch configuration is:
```json
{
	"type": "gdb",
	"request": "launch",
	"name": "Launch UT",
	"target": "/path/to/project/build/unitTests",
	"cwd": "/path/to/project",
	"valuesFormatting": "parseText",
	"internalConsoleOptions": "openOnSessionStart",
	"stopAtEntry": true,
	"showDevDebugOutput": true,
	"printCalls": true
}
```

When I choose 
![image](https://user-images.githubusercontent.com/19170699/207638022-4bfe2291-1990-4943-bfae-816bebfa6438.png)

Then nothing happens and on vscode's `DEBUG CONSOLE` I can see:

```
1-gdb-set target-async on
2-list-features
3-environment-directory "/path/to/project"
4-file-exec-and-symbols "/path/to/project/build/unitTests"
GDB -> App: {"outOfBandRecord":[{"isStream":false,"type":"notify","asyncClass":"thread-group-added","output":[["id","i1"]]}]}
GDB -> App: {"token":1,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[]}}
GDB -> App: {"token":2,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["features",["frozen-varobjs","pending-breakpoints","thread-info","data-read-memory-bytes","breakpoint-notifications","ada-task-info","python"]]]}}
GDB -> App: {"token":3,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["source-path","/path/to/project:$cdir:$cwd"]]}}
-gdb-exit
```

That's it. I don't know what is wrong 😔

When I open ssh to my remote a manualy run: `gdb /path/to/project/build/unitTest` then it loads all symbols correctly and I'm able to run the tests.

**Comment by GitMensch** [comment]
There's no crash visible in your output. You may want to recheck with `"showDevDebugOutput": true, "printCalls": true,` in launch.json, this way we may be able to catch that and return a useful message to the user.

... in any case: if _gdb_ chrashes then this seems to be unrelated to this extension and you may want to close this issue.

To the question: "Are there any other ways to debug this extension on SSH mode?", which I read as "to debug _with_ this extension on SSH remote": sure connecting with [`jeanp413.open-remote-ssh`](https://github.com/jeanp413/open-remote-ssh/issues), then debug. In the case you want to do that with a WSL container, have a look at https://github.com/jeanp413/open-remote-ssh/issues/96.
