### ISSUE TITLE
Over ssh, setting breakpoint doesn't work

### ISSUE THREAD

**Issue by RaphaelMartin83** [WebFreak001/code-debug#369]
If submitting a bug please make sure

- [X] If you are using gdb
  - [X] `gdb --version` >= 7.7.1
  - [X] it works on the command line with `gdb`
  - [X] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

My configuration:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "name": "Launch",
            "target": "The path to the executable on the remote machine",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "ssh": {
                "host": "192.168.0.2",
                "cwd": "a working path",
                "keyfile": "The id_rsa file",
                "user": "keranova"
            }
        }]
}
My program runs properly but:
The issue: Breakpoints don't work
The warning I have: No source file named /home/myUser/dev/src/foo.cpp
The .cpp file path and name change when I change my breakpoint so it's OK but the path added after cwd is full lower case but is supposed to have uppercases. Due to this the remote machine (linux Debian buster) doesn't find the file.
The vscode machine runs on windows 10.

It looks like the breakpoint path is forced to lowercase somewhere in the process between the editor and the gdb command issued on the remote.

**Comment by GitMensch** [comment]
Looks like a duplicate for the fixed (but not released) #346 - no? If yes - please close as duplicate.

**Comment by RaphaelMartin83** [comment]
Yes seems to be the same, thank you.
