### ISSUE TITLE
Error - Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by csholmq** [WebFreak001/code-debug#37]
Haven't used the plugin for a couple of weeks and now it won't fire up.

![image](https://cloud.githubusercontent.com/assets/1297882/13521773/6127e97e-e1eb-11e5-98c7-603c3ca6c380.png)

Version 0.4.2 on VSCode - Insiders 0.10.10

**Comment by csholmq** [comment]
Nevermind. New computer with no GDB installed. Was this included before?

**Comment by WebFreak001** [comment]
Um GDB was never included and probably never will. You might have had it already installed on your old installation

**Comment by csholmq** [comment]
Must have. Weird :)
