### ISSUE TITLE
de-selecting of breakpoints via ui don't work

### ISSUE THREAD

**Issue by GitMensch** [WebFreak001/code-debug#374]
Another issue (not related to variables), is that I cannot de-select a breakpoint. I can delete the breakpoint from debug shell, but not untick it in the UI (the bp is still active even though not clinked in the UI).

_Originally posted by @infn-ke in https://github.com/WebFreak001/code-debug/issues/373#issuecomment-1253551896_

**Comment by GitMensch** [comment]
@infn-ke Please provide log output from a session where you stop on a breakpoint (possibly implied via `stopAtEntry`), create one via ui, then de-activate it, then delete it, ideally with a  `info breakpoint` on the debug command line before/after each step.

I guess the UI shows the deactivated breakpoint as deactivated and removes the deleted ones - but `info break` still shows them?

**Comment by infn-ke** [comment]
To this seems to happen when I enable or disable a breakpoint and target is running. Enable/disable in stopped mode seems to work. So maybe this works as expected or should added/removed breakpoints be reconciled between UI and gdb when target is stopped?

**Comment by GitMensch** [comment]
I see - that's #250 then.
