### ISSUE TITLE
Launch the program as root (with sudo) 

### ISSUE THREAD

**Issue by kakkoyun** [WebFreak001/code-debug#387]
I'm trying to debug a program that needs root privileges. Is there a way to achieve this?

**Comment by GitMensch** [comment]
There are at least two options:

1 start vscode as root (so both the program and the started debugger instance will have root rights)
2 preferred: use a small wrapper script that calls `sudo gdb $*` (or the debugger of your choice) and configure this extension to use it (for example with `gdbpath`)

**Comment by GitMensch** [comment]
Seems to be solved... closing as the hint was added to the readme.

**Comment by kakkoyun** [comment]
Thanks ❤️
