### ISSUE TITLE
Possibility to add a KexAlgorithms option or let user enter wanted custom options in an "args" field

### ISSUE THREAD

**Issue by zaqito** [WebFreak001/code-debug#388]
Hello ! 

I'm currently trying to configure the gdb through ssh to remotely debug on a raspberry pi running a custom embedded linux (made via Buildroot).
When configuring launch.json i made a 'launch over ssh" and filed the fields. But the problem is that i always get a "Error: Handshake failed: no matching key exchange algorithm" error.
I'm pretty sure it's due to the diffie-hellman algo and i was sad noticing there was no way to add this KexAlgorithms option in the launch.json config file.
So i asked myself if there was a way to add custom args in the ssh part but i did not succeed.

Thanks for reading, 
and thanks in advance for any response you could give.

**Comment by GitMensch** [comment]
The reason for this issue is, that SSH is done via `ssh2` dependency which is not configurable this way - see #264 for discussion.
I'm closing this - not because it is solved, but because it is "kind of a duplicate" to keep all information an progress notes in the related issue.

**Comment by GitMensch** [comment]
Hm, maybe it would be enough to update ssh2, _maybe_ even with an unofficial patched version as https://github.com/jeanp413/open-remote-ssh/commit/7fbb9395b055215ccafd49507827f7dcc0546f59 - see https://github.com/mscdex/ssh2/pull/1200 (but that seems to be a newer algo).

@brownts  @WebFreak001 What do you think about upgrading ssh2, maybe to the patched version from @jeanp413 for now?

**Comment by zaqito** [comment]
Ok thanks for the answer.
i'll keep an eye on it.
