### ISSUE TITLE
Add remote debugging

### ISSUE THREAD

**Issue by WebFreak001** [WebFreak001/code-debug#4]
See https://github.com/WebFreak001/code-debug/issues/3

**Comment by bbenoist** [comment]
:+1:

**Comment by bbenoist** [comment]
Thank you for being so quick. When could we expect it to be deployed as an update ?

**Comment by WebFreak001** [comment]
Im currently adding adding breakpoints & pausing while running, because I have found out how to do it. I will release when I have finished it

**Comment by bbenoist** [comment]
OK, I was just impatient :wink: . Thanks for the info!

**Comment by WebFreak001** [comment]
ok released it as 0.2.0
