### ISSUE TITLE
Intellisense?

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#42]
My source code is reasonably colorized, but there is no error detection, no "Show definition," etc., that I can see. What does it take to make that work for C/C++ programs?

**Comment by WebFreak001** [comment]
um thats not the task of the debugger. Look into language plugins for C/C++ instead: https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global https://marketplace.visualstudio.com/items?itemName=mitaki28.vscode-clang
