### ISSUE TITLE
Popup error on hovering.

### ISSUE THREAD

**Issue by memchr** [WebFreak001/code-debug#429]
Apparently, hovering over comments causes the extension to try to evaluate the expression, resulting in many pop-up errors

This is similar to #46 but a bit more disruptive.

---

For example, when I hover on word `cursor` from comment `// don't warp cursor outside the window`, it was evaluated in gdb, resulting in the popup stating `no symbol "cursor" in current context`. I tried to suppress this error but couldn't find the appropriate options.

![image](https://github.com/WebFreak001/code-debug/assets/118117622/6361ab1c-1e30-474a-a133-97d211f76118)

---

using gdb 14.2

**Comment by oltolm** [comment]
I fixed it in this PR https://github.com/WebFreak001/code-debug/pull/438.
