### ISSUE TITLE
Spurious hover-related warnings

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#46]
I have no IntelliSense extensions loaded yet. While stopped at a breakpoint in my C program, if I move the mouse over various words in the program, I get warning messages in the debug console. Notice for example that the word "negative" was from a /* comment */, so it shouldn't try to get its value!

Hovering over a variable name that has a value does seem to work - it (Code or code-debug) shows the value in a hover message.

![spurioushovererrors](https://cloud.githubusercontent.com/assets/7545571/13661791/e175cd38-e652-11e5-8b55-daf2cbd2d9ef.png)

**Comment by WebFreak001** [comment]
Code tells code-debug to get some value and code-debug just always prints the error messages. I should make it so code-debug doesn't show error messages for hovers
