### ISSUE TITLE
Please OS X user manual to README and how to set breakpoint in lldb?

### ISSUE THREAD

**Issue by meritozh** [WebFreak001/code-debug#48]
If submitting a bug please make sure

- [x] use lldb
  - [x] `lldb --version` is apple version
  - [x] it works on the command line with `lldb-mi`

Xcode command tools won't provide `lldb-mi`, but this command is shipped with `Xcode.app`

just one command can make OS X user use this extension.
`ln -s/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi /usr/local/bin/lldb-mi`

And how to configure `launch.json` to make it support breakpoint?

**Comment by WebFreak001** [comment]
These are the languages which have breakpoint support enalbed: https://github.com/WebFreak001/code-debug/blob/master/package.json#L189-L210

Basically if you use some language from that list you can simply hover over the line counter at the left in your files and click the red circle. The red circle indicates a breakpoint, you can also right click the circle and edit it. In that input box you can enter a break condition (for example `i > 40` if you have a variable named `i` and it will only break if `i` is greater than 40)

If you are using a language with no breakpoint support but LLDB/GDB support just make an issue or fork and PR yourself. Its a really simple task which just requires you to add a string to the LLDB/GDB array.

I'm gonna add that `ln` command to the README

**Comment by meritozh** [comment]
Thanks.

I just forget to add `--debug` : (

**Comment by GitMensch** [comment]
For anyone that may come back to this later, the URL with the languages that include breakpoint support referenced was https://github.com/WebFreak001/code-debug/blob/f0f10251e05bcd6fad5d137c21e0f72826cb245e/package.json#L189-L210. It seems more split currently (and I do wonder why "cobol" is listed under lldb-mi, but not under gdb, and _guess_ its common [debuggable] id should be additional gnucobol )
