### ISSUE TITLE
Changing breakpoints while paused doesn't work

### ISSUE THREAD

**Issue by JanKok** [WebFreak001/code-debug#50]
Breakpoints _can_ be set or cleared using the Code UI, but the change has no effect until the next time the Start button is clicked in Code.

For example, I can set some breakpoints through the Code UI, click Start, and Code will stop when a breakpoint is hit. But if I clear the breakpoint via Code UI and then continue, the program will continue to stop at that breakpoint location. Or if I set a new breakpoint during the pause and then continue, Code won't stop at the new breakpoint.

It seems as if Code updates gdb's breakpoints only at Start time, not during pauses.

Or maybe it's another case of improper argument passing to gdb. If I type enable or disable on the input line of the debug console while paused, breakpoints are enabled or disabled as expected. But if type `disable th.c:1403`, I get a message in the debug console: `Bad breakpoint number 'th'` and the breakpoint isn't disabled.

**Comment by WebFreak001** [comment]
do you have the most recent code-debug version? This was fixed in the latest release

To update simply press ctrl-p and type `ext update ` and update all extensions

**Comment by JanKok** [comment]
The new version of code-debug works much better. Thanks! :-)
