### ISSUE TITLE
Buffering prevents output without newlines

### ISSUE THREAD

**Issue by weworld** [WebFreak001/code-debug#51]
Hello, I try to use the debug extension to debug a helloworld C program, but I can not find any output of the program being debugged, although breaks and watches of gdb works.  The vscode Output window only have git and tasks results which is the output of the make program, and the Debug Console window only have gdb debug  info output. Please help! 

The command version gdb 7.11 works all right at Mac OSX10.10.5 machine, and output "hello, world! the value = 100" in the end:
```
jasmine:vscodetes$ gdb helloworld
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin14.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from hello world...Reading symbols from /Users/z01/work/vscodetest/helloworld.dSYM/Contents/Resources/DWARF/helloworld...done.
done.
(gdb) run
Starting program: /Users/z01/work/vscodetest/helloworld 
warning: `/BinaryCache/coreTLS/coreTLS-35.40.1~1/Objects/coretls.build/coretls.build/Objects-normal/x86_64/system_coretls_vers.o': can't open to read symbols: No such file or directory.
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.40.1~1/Symbols/BuiltProducts/libcoretls_ciphersuites.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.40.1~1/Symbols/BuiltProducts/libcoretls_handshake.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.40.1~1/Symbols/BuiltProducts/libcoretls_record.a"
warning: Could not open OSO archive file "/BinaryCache/coreTLS/coreTLS-35.40.1~1/Symbols/BuiltProducts/libcoretls_stream_parser.a"
hello, world! the value = 100[Inferior 1 (process 639) exited normally]
```

If submitting a bug please make sure

- [Y ] If you are using gdb
  - [Y ] `gdb --version` >= 7.7.1
  - [ Y] it works on the command line with `gdb`
  - [ Y] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by WebFreak001** [comment]
The debug console should actually show it in the bottom. Can you try it with some program which outputs lots of logging? Like for example `while(true) { writeln("test"); }` and check if that works. node.js sometimes has problems with buffering on OS X, i have some similar issue related to buffering on another plugin

**Comment by weworld** [comment]
Thanks. It works finally with one line code: flush(stdout).  It seems vscode do not output immediately.

**Comment by WebFreak001** [comment]
oh right no its my code. Its because there is no newline

**Comment by WebFreak001** [comment]
Don't forget to flush in your program because without \n it wont flush automatically
