### ISSUE TITLE
Clear Debug console before start debugging

### ISSUE THREAD

**Issue by weworld** [WebFreak001/code-debug#52]
It seems debug console show more old logs when i stop debug and try to debug again.

```
#include <stdio.h>

int main(int argc, char* argv[])
{
    int a = 10;
    a *= 10;
    while (1) {
        printf("hello, world! the value = %d\n", a);
        a += 10;
        fflush(stdout);
    }
    return 0;
}
```

when start with no break points. Debug console window show more logs util it can't show any thing, then an empty debug console shows. Then i click stop debug button. when i start debug again. There is till no logs show (maybe for there have more old logs not showed before).

Two problem here:
1. when more logs, debug console stucks
2. restart debug not clear old logs 

If submitting a bug please make sure

- [Y ] If you are using gdb
  - [Y ] `gdb --version` >= 7.7.1
  - [ Y] it works on the command line with `gdb`
  - [ Y] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by WebFreak001** [comment]
Eh vscode should do this. In fact the extension has no control about the console, it can only log to it but nothing more

**Comment by weworld** [comment]
If clear debug console window by hand, will handy fix the problem that debugging output not display immediately.

**Comment by WebFreak001** [comment]
This should maybe be reported to vscode but I can't reproduce it

**Comment by weworld** [comment]
I will try to read some vscode to understand what happen. Thanks for your help.

**Comment by WebFreak001** [comment]
Debug console actually gets cleared for me. Try updating vscode and code-debug and try again, otherwise report it to vscode and reopen here
