### ISSUE TITLE
Using gdb from a different toolchain (e.g. arm-none-eabi-gdb)

### ISSUE THREAD

**Issue by mafredri** [WebFreak001/code-debug#53]
Hi,

I tried to look around the configurations but I couldn't find a straightforward way to use gdb from a different toolchain (`arm-none-eabi` in my case), is it possible? If not, could it be made possible to configure which gdb executable to use? This would be useful when performing remote debugging on different architectures.

**Comment by WebFreak001** [comment]
Genius! Why didn't I think of that?

**Comment by mafredri** [comment]
Whoa, that was quick! Thanks a bunch :)

**Comment by WebFreak001** [comment]
Gonna release in a bit, first going to fix #51

**Comment by Seikho** [comment]
Should these settings be in user/project settings instead?
The paths would vary from user to user and wouldn't change per project.

**Comment by WebFreak001** [comment]
Hm that's not really possible to get the debug extension talk to a regular extension. So I can't really access the user settings without manually reading the config json folders.

**Comment by Seikho** [comment]
This seems like a common problem for debug extensions, but debug extensions probably aren't very common 😛 
I'll do some digging on Microsoft/VSCode and raise an issue to see if it can't be resolved.

**Comment by WebFreak001** [comment]
The debug extension is basically a standalone program without any dependency on vscode. There _is_ some code in frontend using vscode APIs but that part is basically a completely separate second plugin. That frontend communicates with my debug extension afterwards using Unix Domain Sockets when its runnings. But at startup the launch config is all I can get without raw access to the file system
