### ISSUE TITLE
invalid lldb command on OSX

### ISSUE THREAD

**Issue by nikharris0** [WebFreak001/code-debug#54]
When starting debug (green play button) the following error is outputted:

```
undefined(lldb) 1-gdb-set target-async on
(lldb) 2-file-exec-and-symbols "/Users/nikharris/source/navitas-hub-emulator/hub-emulator"
undefinederror: '1-gdb-set' is not a valid command.
error: '2-file-exec-and-symbols' is not a valid command.
```

platform: OSX 10.11.3
Visual Studio Code version: 0.10.11
lldb-mi version: 7.4

*launch.json*
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug",
			"type": "lldb-mi",
			"request": "launch",
			"target": "./hub-emulator",
			"cwd": "${workspaceRoot}"
		}
	]
}
```

**Comment by WebFreak001** [comment]
um can you try entering this into your terminal:

```
cd /Users/nikharris/source/navitas-hub-emulator/
lldb-mi hub-emulator
1-gdb-set target-async on
2-file-exec-and-symbols "hub-emulator"
```

If this also tells you "..." is not a valid command then there is something wrong with your lldb installation

**Comment by nikharris0** [comment]
yes, I did that and I'm getting the same errors. Interestingly, I haven't made any changes and the lldb install should be stock. I'll report back more details once I figure it out. Thanks!

**Comment by nikharris0** [comment]
reinstalling xcode via app store solved this, in case anyone else runs into this.
