### ISSUE TITLE
support view memory info?

### ISSUE THREAD

**Issue by hardboydu** [WebFreak001/code-debug#55]

**Comment by WebFreak001** [comment]
Thought of that but vscode does not really provide any place where i could show it. I haven't gotten regular vscode APIs for displaying to work yet but I think I might need another extension for that. Maybe in the future when there is some API for creating views or something via the debugging protocol

**Comment by WebFreak001** [comment]
You can press `Ctrl-Shift-P -> Examine Memory Location` now and enter a memory location to see the raw byte values there
