### ISSUE TITLE
set up path

### ISSUE THREAD

**Issue by micatske** [WebFreak001/code-debug#56]
I am not sure how to set PATH in Ubuntu after install debug? Thanks

**Comment by WebFreak001** [comment]
just install gdb over apt-get install gdb and then it should work. You can test it by typing `gdb` into the console

**Comment by micatske** [comment]
![image](https://cloud.githubusercontent.com/assets/3292292/14187561/ac9031ac-f751-11e5-8ff4-53c336be5100.png)

I have gdb installed, but vscode doesn't find gdb yet. I am trying to use gdb in vscode

**Comment by WebFreak001** [comment]
did you install the debugging extension? Do Ctrl-P then do `ext install webfreak.debug`

Then for your project just follow the instructions in the README. You can just read it here: https://github.com/WebFreak001/code-debug/blob/master/README.md
