### ISSUE TITLE
Call stack rarly works

### ISSUE THREAD

**Issue by jameskozlowski** [WebFreak001/code-debug#63]
When using ARM GDB the call stack rarely displays any information on breakpoints/pause. have not been able to pinpoint when it does work

**Comment by WebFreak001** [comment]
The corresponding gdb commands to the stack command it uses internally are `backtrace` and `where`. Does it work if you debug from the console properly or is the call stack also broken there?

**Comment by kozlojak** [comment]
Not sure what was going on last night, but it seems to be working fine today.

but here are the readouts from the commands
both backtrace and where provide this output
#0  0x00001bbe in updateDisplay (videomemory=0x100010c0 <videoMemory> "") at .\LPCProject\Src\nokia5110.c:125
#1  0x0000153e in main () at .\LPCProject\Src\main.c:72

**Comment by kozlojak** [comment]
I was able to get it to stop working again, not sure what I did, but here is a screen shot including the out put of both of those commands
![untitled](https://cloud.githubusercontent.com/assets/1572408/16178658/1210d81c-3625-11e6-91d3-e3b8cb836cee.png)

**Comment by WebFreak001** [comment]
Hm weird, can you try running `-stack-list-frames` and post the output?

**Comment by kozlojak** [comment]
-stack-list-frames returns:
not available

**Comment by WebFreak001** [comment]
oh right, try `asdf-stack-list-frames` and then it should output something

**Comment by kozlojak** [comment]
That did not work, however I can use "info frame" and I get this

>Stack level 0, frame at 0x10001fd8:
 pc = 0x1e54 in SerialReadByte (.\LPCProject\Src\serialloader.c:21); saved pc = 0x14f4
 called by frame at 0x10001fe8
 source language c.
 Arglist at 0x10001fd0, args: 
 Locals at 0x10001fd0, Previous frame's sp is 0x10001fd8
 Saved registers:
 r7 at 0x10001fd0, lr at 0x10001fd4

**Comment by WebFreak001** [comment]
Now you are able to do `-stack-list-frames` and also the variable view which was stuck in your screenshot will show an error why its hanging

**Comment by GitMensch** [comment]
Solved -> closed.
