### ISSUE TITLE
Examin memory location 

### ISSUE THREAD

**Issue by kozlojak** [WebFreak001/code-debug#64]
I would love a way to examine memory locations with GDB (ARM GDB) via the "x adr" command. by manually entering in locations and lengths, or even better by expanding pointers.

**Comment by WebFreak001** [comment]
Any suggestions how to show this in vscode? Debug extensions have even less control over the UI than regular extensions.

Maybe entering something like `[0x7fffffffddd8+20]` into the `WATCH` section could print the memory there.

However there is a big disadvantage there: the space for that is super small and it couldn't fit lot of data

**Comment by kozlojak** [comment]
I don't know much about VS extensions, but could you read the memory and create a new unsaved file with the data in in?

**Comment by WebFreak001** [comment]
Oh good idea! Didn't even think of that because the debugger doesn't actually have any API for that. However I think with some tricks via the filesystem and interprocess communication I can actually give that data to the plugin part which has the APIs to do that.

You can probably expect this feature to get added within the next 10 days

**Comment by WebFreak001** [comment]
and not a day to late :D

You can now press Ctrl-Shift-P -> Examine Memory Location and then either enter
* a range in the format `from-to` where from and to are hex numbers prefixed with 0x
* a range in the format `from+length` where from is a hex number prefixed with 0x and length is any number
* directly the location as hex number which will display the 32 bytes before that and 768 bytes after that

The hex viewer also has the basic functionality to show the ascii values at the right to find text in the memory
