### ISSUE TITLE
[Bug] CWD option escaped improperly on Windows

### ISSUE THREAD

**Issue by csholmq** [WebFreak001/code-debug#7]
When CWD is not present, a general warning says that `Warning: c:devMyPath: No such file or directory.` As you can see, no slashes are present.

Setting `"cwd": "C:/dev/My/Path"` or `"cwd": "C:\\dev\\My\\Path"` produces the same message. However, setting it to `"cwd": "C:/dev/My/Path/"` (note trailing slash) ends up as 

```
Failed to run command `environment-directory "C:\dev\My\Path\"`: Problem parsing arguments: environment-directory "C:\dev\My\Path\"
An error occured: Problem parsing arguments: environment-directory "C:\dev\My\Path\"
```

Not fluent enough in TypeScript to fix it I'm afraid.

**Comment by WebFreak001** [comment]
I suppose setting it to `"cwd": "C:\\\\dev\\\\My\\\\Path"` works though, right? Because GDB/MI probably has escaped strings and i just pass what the json gives me. Replacing \ with \\ should fix it already in the code

**Comment by csholmq** [comment]
Yes, that is correct.

Perhaps offtopic, but what difference should `environment-directory` do?

**Comment by WebFreak001** [comment]
good question, i think it doesn't do anything. Its just implemented so gdb will show you if you have an invalid cwd

**Comment by WebFreak001** [comment]
Should be fixed
