### ISSUE TITLE
Using file sockets on Windows

### ISSUE THREAD

**Issue by aka-demik** [WebFreak001/code-debug#70]
Got this in Debug console:
```
Code-Debug Utility Command Server: Error in command socket Error: listen EACCES c:\TEMP\code-debug-sockets\Debug-Instance-gwlq
```

vscode: 1.4.0
gdb: 7.11.1
Native debug: 0.11.1

**Comment by WebFreak001** [comment]
this shouldn't be a fatal bug, just a warning in the console that things like examine memory inside the vscode gui wont work

**Comment by aka-demik** [comment]
Breakpoints (and something else) did not work after the update. And I drew attention to this message.
I can not say why, but now it works. I'll post Issue, if I can reproduce it.

**Comment by WebFreak001** [comment]
ok I have updated the error message so it won't draw that much attention
anymore.

Still I need to fix the server on windows in this case
