### ISSUE TITLE
Question/Help : Breakpoints are not hitting

### ISSUE THREAD

**Issue by sherry-ummen** [WebFreak001/code-debug#72]
Hi,

OS: Window 10 64bit
GDB : GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1

I have breakpoints but they do not get hit and the code runs like normal and shows the ouput on the debug console.

Could you please help in understanding what is wrong?

![vscodegdb](https://cloud.githubusercontent.com/assets/2572380/18088720/c6f850c0-6ec4-11e6-9eef-e867ed1be407.png)

**Comment by sherry-ummen** [comment]
When I do it from command line then it looks something like this

C:\cygwin64\bin>gdb.exe "C:\Users\sherr\OneDrive\Edu\Rust\vscodetest\target\debug\vscodetest.exe"
GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from C:\Users\sherr\OneDrive\Edu\Rust\vscodetest\target\debug\vscodetest.exe...(no debugging symbols found)...done.
(gdb)

**Comment by sherry-ummen** [comment]
After doing the whole setup once again . Now I get this error

![2016-08-30](https://cloud.githubusercontent.com/assets/2572380/18102718/46511cf8-6efc-11e6-9b3b-9ff1bab0f01b.png)

**Comment by sherry-ummen** [comment]
![2016-08-30](https://cloud.githubusercontent.com/assets/2572380/18102792/8e98805a-6efc-11e6-9f81-7694f4eee188.png)

**Comment by WebFreak001** [comment]
Seems like GDB is telling code-debug a _wrong_ path, I can probably add a hack to replace `\cygdrive\c` with `C:` to fix the issue because vscode tries to open your file which is in some virtual path from cygwin

**Comment by sherry-ummen** [comment]
Thanks. Actually I fixed it using different GDB module and got it working. I also blogged about it here https://sherryummen.in/2016/09/02/debugging-rust-on-windows-using-visual-studio-code/ .

You can decide whether you would still like to fix it.

**Comment by WebFreak001** [comment]
Yeah adding a workaround which will only run on windows shouldn't break anything and it will make it easier for users who had the same problem as you

**Comment by WebFreak001** [comment]
Also on the forum thing you sent I saw someone asking how to use rustgdb in vscode.

Thats also doable with my extension by just setting `"gdbpath": "rustgdb"` in the debugger launch.json config, just in case you want to add that to your blog post

**Comment by sherry-ummen** [comment]
Hey thanks for that info, ill add it to my blog post.
