### ISSUE TITLE
Feature Request: Add a post-debug task

### ISSUE THREAD

**Issue by newbrain** [WebFreak001/code-debug#73]
I'm using this extension for embedded debugging, through OpenOCD and other gdb servers.

**Feature request:**
Add a post-debug task, to be run when the debug session is stopped.

**Rationale:**
Programs that behave like a gdbserver process and connect to the target board via USB/JTAG are often used to debug embedded systems.
A typical example is OpenOCD or, say, the Texas Debug Server.
They can easily enough be launched and correctly configured (MCU type, JTAG/SWD debugger, flash algorithms etc.) for the debugged board by using a _pre-launch_ task and the _autorun_ command list.

Unfortunately there's currently no easy way to stop them automatically at the end of the session.

So, a post-debug task to perform process clean up would be a welcome feature.
As an alternative, or as a possible additional feature, a list of commands to run when the "STOP" icon is pressed (similar to the _autorun_ item) could be considered.

**Comment by WebFreak001** [comment]
Hm I don't actually think this is possible with the debug adapter APIs. Basically the debug adapter is running in a separate process without any access to vscode APIs. I have an additional debugger extension bundled with the debug adapter, but it can't talk with the adapter because vscode spawns it and only vscode has access to it. There is also no event for debugger stop which I could use in my extension.

So instead I will create an issue on the vscode project so they can add a postDebugTask to all debuggers and I will also add commands to run after debugging

**Comment by WebFreak001** [comment]
Put up the issue here now: https://github.com/Microsoft/vscode/issues/11522

**Comment by WebFreak001** [comment]
Then again I am not sure if running commands should be done by the extension. When they implement the postDebugTask feature, it isn't really required anymore. The only place where it would be useful is the SSH debugging

**Comment by newbrain** [comment]
Thanks for the outstanding support!
I suggested something similar to the _autorun_, as the debug server I most use is OpenOCD, which supports the "monitor exit" command, so it would easy to have it cleanly stopped from gdb itself.
For the specific case, I'll try define _quit-hook_ inside autorun, so that's fine.

Thanks also for adding the vscode issue, I'm not into the intricacies of the extension interfaces...could have noticed, though, that _pre-launch_ is supported by the built-in vscode debug support.

I think we can close the issue.

**Comment by WebFreak001** [comment]
Using the gdb facilities to run code at quit is probably the best idea. When code-debug runs the quit event GDB is closed already and I can't run any further commands. Also running commands after calling quit does not sound very safe to me

**Comment by bergus** [comment]
@newbrain Can you share your working configuration, please?
