### ISSUE TITLE
`no source file named <absolute_path>` when mouse clicking for debug breakpoint

### ISSUE THREAD

**Issue by payonel** [WebFreak001/code-debug#74]
First of all, thanks for your hard work!

cpp project
Native Debug version: 0.12.2
gdb version: GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-47.el6
works on command line? yes
cwd: workspace root is /home/payo/src -- this is where `make` is run

related launch.json config
```
{
    "name": "ssh-Debug",
    "type": "gdb",
    "arguments": "-i 24",
    "request": "launch",
    "target": "relative/path/to/binary",
    "cwd": "${workspaceRoot}",
    "autorun": ["set substitute-path /home/vmuser/src /home/payo/src", "break func"],
    "ssh": {
        "forwardX11": false,
        "host": "vm-hostname",
        "cwd": "/home/vmuser/src/",
        "keyfile": "/home/payo/.ssh/id_rsa",
        "user": "vmuser"
   }
},
```

**What Happens**
1. run debug mode for "ssh-Debug"
2. gdb starts, the remote process starts
3. `func` is hit, *in foo/ts.cpp* and breaks correctly at the start the method
4. mouse click in left-hand column to add a breakpoint on line `20` does not work
* icon under mouse is a gray "Unverified Breakpoint"
* "DEBUG CONSOLE" prints `No source file named /home/vmuser/src/foo/ts.cpp.`

**Work around**
In "DEBUG CONSOLE", run `break ts.cpp:20` - which succeeds. Note no breakpoint is shown visibly in the editor, but `continue` or pressing `F5` both correctly run and break at line `20`.

Note that `/home/payo/src` is actually a sshfs mounted point to `/home/vmuser/src` - so everything in `/home/vmuser/src` is definitely availables in `/home/payo/src`.

Note that `ts.cpp` is NOT in the root of project folder path.
Also Note that `list` (in gdb debug console) does NOT work, unless I `cd` to `foo/` first.

**Comment by payonel** [comment]
`pwd` in gdb DEBUG CONSOLE shows the project root on the remote machine (good)
the path in the error, `No source file named /home/vmuser/src/ts.cpp.` does actually exist

**Comment by payonel** [comment]
also, setting breakpoints before running the debug session (mouse click in left column) fails in the same way (unverified breakpoints and no such file error message on the debug console)

**Comment by WebFreak001** [comment]
Hm for me gdb over ssh works, can you also send a simple folder layout/tree containing `relative/path/to/binary` and `foo/ts.cpp`

Using your current config the folder layout on the remote machine should be like this:
```
/home/vmuser/
  src/
    relative/path/to/binary
    foo/ts.cpp
```
and on your local machine:
```
${workspaceRoot}/
  relative/path/to/binary
  foo/ts.cpp
```

if you dont have the src folder as workspace root (opened folder in vscode), then you need to change the local cwd to `${workspaceRoot}/src`

**Comment by payonel** [comment]
The situation seems worse now. The path is just weird. (note, these paths are slightly different than first reported)

`Source /home/local/data/home/vmuser/repos/sandbox/main.cpp is not available.`
1. It should be using my local path: `/home/local/ANT/payo/code/sandbox/main.cpp`
2. Even if it was supposed to be a remote path, it should be `/data/home/vmuser/repos/sandbox/main.cpp`

g++ version: 5.4
gdb: 7.11.1
native debug: 0.12.2
vscode: 1.5.2

I created a test project, sandbox

I also removed the ~/.vscode/extensions folder, and reinstalled extensions, also am running a fresh "install" of vscode (unpacked `code-stable-code_1.5.2-1473686317_amd64.tar.gz`)

Note that the example ssh gdb config in your readme (as shown in the extensions viewer in vscode) doesn't have a "type" nor a "name". I'm using "gdb" for type. It appears "name" isn't required - makes sense if it is the only config defined (which in this test for me, it is)

```
        {
            "request": "launch",
            "type": "gdb",
            "target": "./a.out",
            "cwd": "${workspaceRoot}",
            "autorun": ["break main"],
            "ssh": {
                "forwardX11": false,
                "cwd": "/home/vmuser/repos/sandbox/",
                "password": "password",
                "user": "vmuser",
                "host": "vmhost"
            }
        }
```

directory structure of local
```
<laptop>/home/local/ANT/payo/code/sandbox:pwd -P
/home/local/ANT/payo/code/sandbox
<laptop>/home/local/ANT/payo/code/sandbox:ls -lRa
.:
total 152
drwxr-xr-x  3 payo users  4096 Sep 16 13:39 .
drwxr-xr-x 11 payo users  4096 Sep 16 10:52 ..
-rwxr-xr-x  1 payo users 30512 Sep 16 13:39 a.out
-rwxr-xr-x  1 payo users   186 Sep 16 11:43 build.sh
-rw-r--r--  1 payo users   427 Sep 16 11:28 main.cpp
drwxr-xr-x  2 payo users  4096 Sep  9 09:27 .vscode

./.vscode:
total 24
drwxr-xr-x 2 payo users 4096 Sep  9 09:27 .
drwxr-xr-x 3 payo users 4096 Sep 16 13:39 ..
-rw-r--r-- 1 payo users  667 Sep  8 14:54 c_cpp_properties.json
-rw-r--r-- 1 payo users 1383 Sep 16 13:51 launch.json
-rw-r--r-- 1 payo users   79 Aug  3 14:04 settings.json
-rw-r--r-- 1 payo users  242 Jul 22 15:46 tasks.json
```

directory structure of remote (vm)
```
<vmhost>/home/vmuser/repos/sandbox:pwd -P
/data/home/vmuser/repos/sandbox
<vmhost>/home/vmuser/repos/sandbox:ls -la
total 48K
drwxr-xr-x. 2 vmuser users 4.0K Sep 16 21:02 .
drwxr-xr-x. 6 vmuser users 4.0K Sep 16 18:23 ..
-rwxr-xr-x. 1 vmuser users  30K Sep 16 20:39 a.out
-rwxr-xr-x. 1 vmuser users  186 Sep 16 18:43 build.sh
-rw-r--r--. 1 vmuser users  427 Sep 16 18:28 main.cpp
```

Things I've tried. Note that using `set substitute-path` is having NO change on any of these results.

[I'll list changes I tested, and the affect they had on the "source is not available" ]

Changes to `cwd` (not `ssh.cwd`)
`cwd: ""`
`cwd: "/home"`
`cwd: "/home/local"`
`cwd: "/home/local/ANT"`
`cwd: "/home/local/ANT/payo"`
All resulted in:
`Source /data/home/vmuser/repos/sandbox/main.cpp is not available.`

Then I realized it was prefixing the search path with (essentially) the absolute path of `cwd`, and 4 dirs up from there
For example `${workspace}../../../../` is `/home/local`
My full workspace dir is
`/home/local/ANT/payo/code/sandbox`
I tested making a test path: `/home/local/ANT/payo/code/sandbox/foo/bar`
and: `"cwd": "/home/local/ANT/payo/code/sandbox/foo/bar"`

Sure enough, the "failed" path when debugging was:
`Source /home/local/ANT/payo/data/home/vmuser/repos/sandbox/main.cpp is not available.`

ANY invalid path (e.g. non absolute paths, or dirs that didn't exist)
`cwd: "/home/local/ANT/payo/code`
resulted in:
`/home/data/home/vmuser/repos/sandbox/main.cpp `

I thought it strange the path appeared to be concat'd in this way
So I tested with different types of paths

I found if I change `ssh.cwd` to "/", and make a copy of `a.out` at root, and `cwd` is still `/home/local/ANT/payo/code/sandbox/foo/bar`, then my failed path is:
`Source /home/local/ANT/payo/code/sandbox/foo/bar/data/home/vmuserrepos/sandbox/main.cpp is not available.`

At this point, I tried using `set substitute-path` again, and it started making a difference. But anything I set in `ssh.cwd` was APPENDED to my `cwd` value (minus some 4 dirs of depth). So the only way I could get vscode to show the source was:
`cwd: "${workspace}`
`ssh.cwd: "/"`
`target: "/a.out"` # yes, at root
`"autorun":"set substitute-path /home/vmuser/repos/sandbox /"`

Now the source files are found, but, gdb commands in the debug console do not work (note, throughout ALL the testing above, gdb commands (e.g. `list`, `where`, `source info`) where all working great, now with vscode finding the source, the gdb commands cannot find the source files.

**Comment by payonel** [comment]
Also I found that with vscode working with my weird `ssh.cwd` at `/`, I could set break points in `main.cpp`, and continue, and vscode would stop at the breakpoints as expected, even though their icon glyph was "unverified".

Note, breakpoints via gdb commands in the debug console, still cannot find the source (As noted at the very end of my last comment)
```
list
21	main.cpp: No such file or directory.
```

**Comment by payonel** [comment]
I am able to run my main project using this workaround, but local vars in the debug windows are not found, and gdb in the debug console has no idea what the source is, and print `var` name fails as well.

**Comment by WebFreak001** [comment]
Can you debug the app and run to some breakpoint and send the output of `-stack-list-frames` in here? I want to see what path gdb gives code-debug

**Comment by payonel** [comment]
Using my work around shown above, and breaking on main:

```
list
27	main.cpp: No such file or directory.
-stack-list-frames
{"token":22,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["stack",[["frame",[["level","0"],["addr","0x000000000040082d"],["func","main"],["file","main.cpp"],["fullname","/main.cpp"],["line","27"]]]]]]}}
```

So it thinks main is at `/main.cpp` ? That makes sense -- that workaround is replacing the path to /

I'll retest using this launch config:

```
{
            "name": "ssh-Debug",
            "type": "gdb",
            "arguments": "",
            "request": "launch",
            "target": "a.out",
            "cwd": "${workspaceRoot}",
            "autorun": ["set substitute-path /home/vmuser/repos/sandbox /home/local/ANT/payo/code/sandbox", "break main"],
            "ssh": {
                "forwardX11": false,
                "host": "vmhost",
                "cwd": "/home/vmuser/repos/sandbox",
                "keyfile": "/home/local/ANT/payo/.ssh/id_rsa",
                "user": "elemental"
            }
        }
```

Again, breakpoint hit but source not found:
`Source /home/local/data/home/vmuser/repos/sandbox/main.cpp is not available.`

```
list
23	    const char* sz = "";
24	    cout << (*sz == '\0') << endl;
25	    cout << test() << endl;
26	
27	    return 0;
28	}
-stack-list-frames
{"token":10,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[["stack",[["frame",[["level","0"],["addr","0x00000000004007df"],["func","main"],["file","main.cpp"],["fullname","/data/home/vmuser/repos/sandbox/main.cpp"],["line","23"]]]]]]}}
```

**Comment by WebFreak001** [comment]
aha! It doesn't work because the fullname is prefixed with `/data/`, code-debug tries to make that path relative to the cwd you specified for `ssh.cwd`, which it can't do because the folder it tries to make it relative in is inside of the target folder. Does debugging work if you add `/data/` before the ssh.cwd? If it works then breakpoints, etc should work in there

**Comment by payonel** [comment]
on these systems, /home is a symlink to /data/home
And yes, setting `ssh.cwd` to `/data/home/vmuser/repos/sandbox` seems to have fixed things.

:) Nice work. Any plans to support symlinks in the path? [note for me, it's not a problem at all to use the true path]

**Comment by WebFreak001** [comment]
hm I don't think its efficiently possible to check the whole path for symlinks and symlinks in symlinks and save all versions to correctly identify the path from what gdb gives me. So for now I am just gonna leave it like this so you need to set it in the config properly
