### ISSUE TITLE
Attaching via SSH

### ISSUE THREAD

**Issue by andyneff** [WebFreak001/code-debug#83]
Is *attaching* to a running process via ssh (connecting to a Linux server from Windows in my case) currently possible? I was able to get *launching* working (with #78 still there)

If it is not currently possible, is this a feature you are interested in adding? I'm very interested in this scenario as it is the only way to debug my current infrastructure.

**Comment by WebFreak001** [comment]
Oh right that isn't actually implemented yet. Might do it in the future.

Relevant code for this starts at https://github.com/WebFreak001/code-debug/blob/master/src/gdb.ts#L110 and basically only needs some argument in the current ssh function to support this. Then the code should be the same for the LLDB module.

**Comment by WebFreak001** [comment]
`lldb` didn't really work, maybe in the future

**Comment by konstantin-mephi** [comment]
> Oh right that isn't actually implemented yet. Might do it in the future.
> 
> Relevant code for this starts at https://github.com/WebFreak001/code-debug/blob/master/src/gdb.ts#L110 and basically only needs some argument in the current ssh function to support this. Then the code should be the same for the LLDB module.


Is attaching to a running process via ssh (connecting to a Linux server from Windows in my case) currently possible?

**Comment by andyneff** [comment]
@konstantin-mephi A lot had changed over the years.

VSCode's remote debugger has kinda gone off the deep end recently via installing a server on the remote system, but you can look at https://code.visualstudio.com/docs/remote/ssh and see if this works for you.

**Comment by WebFreak001** [comment]
on code-debug side this hasn't been implemented, though you might have some success with alternative methods like that remote debugging.

**Comment by konstantin-mephi** [comment]
Thank you, for your answers!
