### ISSUE TITLE
Enable breakpoints for Vala?

### ISSUE THREAD

**Issue by McBits** [WebFreak001/code-debug#85]
I've been looking for a decent way to step through Vala code. It looks like gdb with this extension actually works for Vala *almost* right out of the box. The only thing I had to do was add "vala" to the list of languages under the "enableBreakpointsFor" (at least for gdb, not sure about the others) in package.json. Perhaps a pull request is more work than it's worth for a one-liner, but I can submit one if you'd like to add this.

**Comment by WebFreak001** [comment]
If it also works for lldb you should also add it to the list of supported languages there. It would be nice if you could then submit a PR
