### ISSUE TITLE
Extension hungs up when GDB's messages are not in English

### ISSUE THREAD

**Issue by nobig** [WebFreak001/code-debug#86]
Tested in Ubuntu 16.04. When the env variable "LANGUAGE" is set to something different to "en_GB" or "en_US", GDB translates some of the MI console output to the local language, but MI doesn't seem to be designed to deal ith UTF-8, resulting in the insertion of escape characters that breaks the MI output parser.

In particular, in my setup GDB converts
`~[Thread debugging using libthread_db enabled]\n`
to
`~[Depuraci\303\263n de hilo usando libthread_db enabled]\n`
which makes the extension crash with a "Debug adapter process has terminated unexpectedly" message.

For now, I use the workaround of launching VS Code with LANGUAGE set to "en_US", which makes everything work without problem.

**Comment by WebFreak001** [comment]
dup of #77, will add a workaround for now which will just show these raw messages then if the line cannot be parsed
