### ISSUE TITLE
GDB reverse debug

### ISSUE THREAD

**Issue by mxre** [WebFreak001/code-debug#88]
Are there any plans to support GDB reverse debug?

reverse debug allows retracing the steps the program took to get to the current breakpoint. In order to do this one mus run `record` after `start` the program can than be analysed with `reverse-step` akin to `step`.

This GDB feature is (I think) similar to Microsoft's IntelliTrace in VisualStudio

**Comment by WebFreak001** [comment]
It's already implemented since d704af2501168126f6979b2ac784d59d84b3fc98
