### ISSUE TITLE
Enhancement for extended-remote target

### ISSUE THREAD

**Issue by mdelete** [WebFreak001/code-debug#91]
Hi @WebFreak001! Great work on your VS Code plugin! I am trying to replace the dreaded Eclipse for debugging microcontrollers and stumbled upon VS Code and Native Debug. However, the configuration options available did not support the _extended-remote_ target of _GDB_, which would be nice to have for some debugging hardware.

The following is a works-for-me style hack that enables me to happily debug Cortex M microcontrollers using an external USB debugger like [Black Magic Probe](https://github.com/blacksphere/blackmagic/wiki):

### backend/mi2/mi2.js:176 ff. 

    attach(cwd, executable, target) {
        this.log("stdout", "attaching " + target); // added
        return new Promise((resolve, reject) => {
            let args = [];
            if (executable && !nativePath.isAbsolute(executable))
                executable = nativePath.join(cwd, executable);
            if (!executable)
                executable = "-p";
            if (target.startsWith("extended-remote")) // added
                args = this.preargs; // added
            else // added
                args = args.concat([executable, target], this.preargs);
            this.process = ChildProcess.spawn(this.application, args, { cwd: cwd });
            this.process.stdout.on("data", this.stdout.bind(this));
            this.process.stderr.on("data", this.stderr.bind(this));
            this.process.on("exit", (() => { this.emit("quit"); }).bind(this));
            Promise.all([
                this.sendCommand("gdb-set target-async on"),
                this.sendCommand("environment-directory \"" + escape(cwd) + "\""), // appended comma
                this.sendCommand("target-select " + escape(target)), // added (this should only be here for extended-remote)
                this.sendCommand("file-symbol-file \"" + escape(executable) + "\"") // added (this should only be here for extended-remote)
            ]).then(() => {
                this.emit("debug-ready");
                resolve();
            }, reject);
        });
    }
    
### launch.json:

    {
      "version": "0.2.0",
      "configurations": [
        {
          "name": "BMPv2",
          "type": "gdb",
          "request": "attach",
          "gdbpath": "~/gcc-arm-none-eabi-5_2-2015q4/bin/arm-none-eabi-gdb",
          "target": "extended-remote /dev/cu.usbmodemXXXXXXXX",
          "executable": "my-arm-executable.elf",
          "cwd": "${workspaceRoot}",
          "autorun": [
            "monitor tpwr enable",
            "monitor swdp_scan",
            "attach 1",
            "load my-arm-executable.elf"
          ]
        }
      ]
    }

**Comment by WebFreak001** [comment]
Does it still work if you change
```ts
this.sendCommand("target-select " + escape(target)),
```
to
```ts
this.sendCommand("target-select \"" + escape(target) + "\""),
```
?

**Comment by mdelete** [comment]
It would **not** work if you put the parameter after _extended-remote_ in quotes, even if properly escaped with backslashes ;). The _escape()_ is fine, though.

**Comment by WebFreak001** [comment]
The escape will replace " with \" and replace \ with \\, so unless in quotes it will break things

**Comment by conioh** [comment]
@WebFreak001:

Hi. I'm probably doing something wrong, but `extended-remote` doesn't work for me.

I get the following error:

> Failed to attach: extended-remote localhost:12345: No such file or directory. (from target-select remote extended-remote localhost:12345)

My configuration is:
```
{
    "type": "gdb",
    "request": "attach",
    "name": "Attach to gdbserver",
    "target": "extended-remote localhost:12345",
    "gdbpath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/VC/Linux/bin/gdb/7.9/x86_64-linux-gnu-gdb.exe",
    "remote": true,
    "cwd": "${workspaceRoot}",
}
```

However if I simply launch `x86_64-linux-gnu-gdb.exe` the following works:
```
(gdb) target extended-remote localhost:12345
Remote debugging using localhost:12345
(gdb) run
Starting program:
warning: Could not load vsyscall page because no executable was specified
try using the "file" command first.
[Inferior 1 (process 217) exited normally]
(gdb)
```
(Lets ignore the warning for now. I see the executable running.)

I must be doing something really stupid, but I don't see what it is.

**Comment by DeadRabbits307** [comment]
Is a extended-remote support now possible with native debug? I still can not get a setup with a working "restart" functionality in the VS Code debugger. If I am wrong, how would a correct `launch.json` look like? 

On the target I start `gdbserver `as following:
`gdbserver --multi :2345`

May launch.json:
```
{   
            "type": "gdb",
            "request": "attach",
            "name": "myprogdebug via gdbserver",
            "executable": "./myprog",
            "target": "xx.xx.xx.xx:2345",
            "remote": true,
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "gdbpath": "aarch64-linux-gdb",
            "env": {
                "PATH": "/path/to/cross-compiler:${env:PATH}"
             },
            "printCalls": true,
            "autorun": ["b 27", "set remote exec-file myprog"]
}
```

**Comment by WebFreak001** [comment]
here is the example config I added with the commit: https://github.com/WebFreak001/code-debug/commit/318ece44cf3a5d51222a9c2e8031b7c1fdc46894#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R373

if you have more questions, make a separate issue

**Comment by DeadRabbits307** [comment]
Thank you for your quick reply. 

Unfortunately this config for Microcontrollers does not help. I use a target running an embedded OS build with buildroot. 

I will open a new issue with more information.
