### ISSUE TITLE
Configure gdb path

### ISSUE THREAD

**Issue by LuisAyuso** [WebFreak001/code-debug#94]
Hi there,
Terrific job in this extension.

I would like to configure the path to the gdb executable to use. It should not be too much work to add a configuration variable, and default it to gdb.
I guess it could be useful as well in the case of lldb.

**Comment by WebFreak001** [comment]
Set `gdbpath` or `lldbpath` in your launch config

**Comment by WebFreak001** [comment]
As to why it isn't implemented as normal vscode setting: Debugger extensions don't have access to that, I would need to add it to the frontend part of the extension + make it always load, no matter what project/language/etc + the debugger would need to wait for a connection from the frontend and I don't have any good interprocess communication on windows, which would mean it wouldn't work at all

**Comment by EmSyndio** [comment]
keep getting "Path must be a string. Received undefined"

tried setting `path` or `gdbpath` but doesn't help. any insight?

**Comment by WebFreak001** [comment]
Here an example for a correct config:
```
{
	"name": "Start Debugging",
	"type": "gdb",
	"request": "launch",
	"target": "./gdbtest",
	"cwd": "${workspaceRoot}",
	"gdbpath": "lldb-mi"
}
```

**Comment by EmSyndio** [comment]
thanks... i guess `"gdbpath": "lldb-mi"` is counter intuitive...

**Comment by WebFreak001** [comment]
Use lldb as debugger instead of gdb if you actually use lldb. lldb-mi is just an example for any executable!
